### ISSUE TITLE
Exception: Mismatched masterKeyRevs

### ISSUE THREAD

**Issue by PsychOsmosis** [blawar/nut#10]
When trying to remove title rights from two recent publicly released NSPs, I get a "mismatched masterkeyrevs" exception (displayed masterkeyrev = 0x0). The calculated titlekey is also different from the titlekey normally obtained from said games using the rights ID.

My guess is the NSPs were reencoded on master_key_00 by the release team for maximum compatibility with all firmwares and therefore nut finds that the key used to encode the game is not the one that's supposed to be used and just stops with an exception when this happens.

Is there some way to let the script do its job despite the masterKeyRevs mismatch?
Thank you very much for the great tool!!

**Comment by PsychOsmosis** [comment]
Into The Breach [010057d00b612000][v0].nsp

But it also does the same thing with   The Messenger [0100dc300ac78000][v0].nsp

**Comment by PsychOsmosis** [comment]
Output from nut.py --remove-title-rights :

rightsId =      0x10057d00b6120000000000000000005
titleKeyDec =   b'1a477cf270cc66e74f9eb9cc54e44633'
masterKeyRev =  0x0
Exception: Mismatched masterKeyRevs!
fin


Output from nut.py -i (Ticket section) :

       Ticket

        File Path: 010057d00b6120000000000000000005.tik
        File Size: 704
        signatureType = TicketSignature.RSA_2048_SHA256
        keyType = 0
        masterKeyRev = 0
        ticketId = 0000000000000000
        deviceId = 0000000000000000
        rightsId = 0x10057d00b6120000000000000000005
        accountId = 00000000
        titleKey = 0xee8494ed9b0f28144d3504357ce900f3
        titleKeyDec = b'1a477cf270cc66e74f9eb9cc54e44633'

**Comment by blawar** [comment]
Yeah your ticket has definitely been modified, how many times did you attempt to remove the title rights with nut?  Do you have another copy of the NSP that you know is not modified?

**Comment by blawar** [comment]
Also, please edit out / censor titleKey and titleKeyDec

**Comment by PsychOsmosis** [comment]
Done. Nah I never used CDN to get NSPs. I actually never used NSPs before, only XCI. But those two titles never got a cartridge release.

I attempted to remove the rights like 30 times (doing multiple attempts with different masterkey revisions and other things to understand what is going wrong).

**Comment by PsychOsmosis** [comment]
I see... And there's no way to make it work with modified NSPs? It would be very useful for me if I could get it to work with scene releases.

**Comment by blawar** [comment]
You can  run nut.py -i path/to/nsp  to get an info dump, look for bdd9bb0fe0b5a840870d028ed8d0ad81.nca and see what it is reporting for the title rights field, and the keyblob field.

If titlerights are still enabled, you can hexedit your ticket to change the masterKey revision.

**Comment by blawar** [comment]
also see what its reporting the master key revision as for that NCA.

**Comment by PsychOsmosis** [comment]
File Path: bdd9bb0fe0b5a840870d028ed8d0ad81.nca
        File Size: 283459584
        magic = b'NCA3'
        titleId = 010057D00B612000
        rightsId = b'010057d00b6120000000000000000005'
        isGameCard = 0x0
        contentType = Content.PROGRAM
        cryptoType = Crypto.NONE
        Size: 283459584
        crypto master key: 2
        crypto master key2: 5
        key Index: 0
        key Block: b'\x91\xde\xa3X\x9aV\xe4\xfa\x1c\xe6\nD@\t\xe7\xd8'
        key Block: b'\x91\xde\xa3X\x9aV\xe4\xfa\x1c\xe6\nD@\t\xe7\xd8'
        key Block: b'\x91\xde\xa3X\x9aV\xe4\xfa\x1c\xe6\nD@\t\xe7\xd8'
        key Block: b'\x91\xde\xa3X\x9aV\xe4\xfa\x1c\xe6\nD@\t\xe7\xd8'

**Comment by blawar** [comment]
the ticket output from that same info command, does it match this?
```
Ticket

        File Path: 010057d00b6120000000000000000005.tik
        File Size: 704
        signatureType = TicketSignature.RSA_2048_SHA256
        keyType = 0
        masterKeyRev = 5
        ticketId = 0000000000000000
        deviceId = 0000000000000000
        rightsId = 0x10057d00b6120000000000000000005
        accountId = 00000000
        titleKey = xxxxxxxxxxxxxxxxxxxxxxxx
        titleKeyDec = b'xxxxxxxxxxxxxxxxxxxxxxxx'
```

**Comment by PsychOsmosis** [comment]
Nope, it's    masterKeyRev = 0

**Comment by blawar** [comment]
i'm an idiot, you posted that above.  ignore my last message.  Im going to do some research to see if I am reading that field wrong.

**Comment by blawar** [comment]
does that game install and play fine as is?  also which scene nsp is this?

**Comment by PsychOsmosis** [comment]
No problem. Alright, thank you very much for taking the time to figure this out.
Do you have a donation link / Patreon or something?

**Comment by blawar** [comment]
Make any donations to male domestic violence shelters.  Thank you.

**Comment by PsychOsmosis** [comment]
Alright, I'll look for one in my area!

It's ISOSLAND's release. There's no team information in the post but it was posted by the site admin, so I'm guessing it works. I don't really want to try it out as is 'cause I'm not banned yet (and still update my XCIs using the official servers) and don't want to add fake tickets to my ticket blob..!

**Comment by blawar** [comment]
There is a solution here:  unpack your nsp nut.py -x path/to/nsp, open up the ticket file with a hex editor, change the masterKey field to 5, save it, then repack the NSP.

If nut removes the titlerights successfully, then you should unpack again, delete the ticket file, then re-pack.  I know  thats a bit of a process but it should fix your issue.

**Comment by blawar** [comment]
the command to repack is nut.py -c name.of.new.file.nsp folderwithExtractedContents/*

**Comment by PsychOsmosis** [comment]
Alright, I'll try this out. But (as stated above in one of my edits), when I tried to unpack/repack as part for my attempts at figuring it out, I got the following :

nut.py -c "D:\Documents\Nintendo Switch Homebrew\nut\Into The Breach [010057d00b612000][v0]"

[...]
PermissionError: [Errno 13] Permission denied: 'D:\Documents\Nintendo Switch Homebrew\nut\Into The Breach [010057d00b612000][v0]'

Did I input the command wrong or is it a Windows permissions thing?

**Comment by blawar** [comment]
-c is for creating a file, -x is for extracting.  you specified a folder not a filename for -c.  use the command I posted about.  make sure you use a new name for the newly created nsp (dont overwrite any files)

**Comment by blawar** [comment]
Assuming that folder is where your extracted bits are, you should use this command:
```
nut.py -c into.the.breach.nsp "D:\Documents\Nintendo Switch Homebrew\nut\Into The Breach [010057d00b612000][v0]\*"
```

**Comment by PsychOsmosis** [comment]
Alright! My toddler is getting impatient so I'll do this later tonight and report back.
Thanks a lot for taking the time to help me in this matter!!

**Comment by blawar** [comment]
You're welcome.  The  byte you want to edit is at offset 0x286 in the ticket file, should be 05

**Comment by PsychOsmosis** [comment]
I've done the hex edit, but when I try to repack (using -c), I get the following error :

creating into.the.breach.nsp
        Repacking to NSP...
Traceback (most recent call last):
  File "D:\Documents\Nintendo Switch Homebrew\nut\nut.py", line 577, in <module>
    nsp.pack(args.file)
  File "D:\Documents\Nintendo Switch Homebrew\nut\Fs\Nsp.py", line 452, in pack
    hd = self.generateHeader(files)
  File "D:\Documents\Nintendo Switch Homebrew\nut\Fs\Nsp.py", line 488, in generateHeader
    fileSizes = [os.path.getsize(file) for file in files]
  File "D:\Documents\Nintendo Switch Homebrew\nut\Fs\Nsp.py", line 488, in <listcomp>
    fileSizes = [os.path.getsize(file) for file in files]
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\Documents\\Nintendo Switch Homebrew\\nut\\Into The Breach [010057d00b612000][v0]\\*'

I tried troubleshooting it and, however I seem to input the filepath, it doesn't work.
I tried the following :
D:\IntoTheBreach\*
D:\IntoTheBreach\*.*
D:\IntoTheBreach\
\IntoTheBreach\   (in nut.py's folder)
\IntoTheBreach\*
\IntoTheBreach\*.*

I also tried everyone of these permutations with "/" instead of "\", to no avail.

After a few Google searches, I found the following information, which seems to make sense :

"Apparently, Wildcards -as shown in the docs- are not being supported on Windows.

Example: pyminifier -d "C:\Users\admin\Desktop\Projects\Python 3.5.1\sysAuth\New" "C:\Users\user\Desktop\Projects\abc\xyz\*.py" gives error OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\user\\Desktop\\Projects\\abc\\xyz\\*.py'

However, when a definite filename in the directory is give, like "C:\Users\user\Desktop\Projects\abc\xyz\helloWorld.py", PyMinifier works perfectly.

This is not a problem with Linux, but for compatibility, I think a different method for going through directories should be used."
(source : https://github.com/liftoff/pyminifier/issues/45)

**Comment by blawar** [comment]
wildcard works on windows, i use it everytime when I pack NSP's.  But you dont need the wild card, just specify each file one by one.  nut.py -c new.nsp file1 file2 file3

**Comment by PsychOsmosis** [comment]
It worked!! It all worked!!

```
Ticket

        File Path: 010057d00b6120000000000000000005.tik
        File Size: 704
        signatureType = TicketSignature.RSA_2048_SHA256
        keyType = 0
        masterKeyRev = 5
        ticketId = 0000000000000000
        deviceId = 0000000000000000
        rightsId = 0x0
        accountId = 00000000
        titleKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        titleKeyDec = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Thank you so very much for everything!!

One last question, is the offset (0x286) for the hex edit the same for every NSP?
If I want to do the same process for my second NSP, it will work with 0x286?

**Comment by PsychOsmosis** [comment]
Now that I think about it, I also have two NSPs for the updates (one for each game).
Can I unpack the update, add its NCAs to the original NSP folder and repack the lot for a Game+Update.nsp?? If so, which files from the update NSP must I add to the game one?

**Comment by blawar** [comment]
This may actually be a bug in the CDNSP code Nut is using.  It appears the offset is incorrect, I just committed a fix, go ahead and update and it should fix your issue.

**Comment by PsychOsmosis** [comment]
Alright, I'll try this out! I just tested the two games (with the update NSP) and they both work flawlessly with the method you described previously!! They both have their rights removed AND no fake ticket in the console's ticket blob!!

If you don't mind, I will write up a tutorial on how to do the whole process for the community and post it on GBATemp (giving you the whole credit of coming up with the process, of course). I didn't find this information anywhere when I was researching how to install NSPs while mitigating the ban risk by not installing fake tickets, so I'm pretty sure it would help a lot of people to write up a detailed tutorial on how to do it.

Of course, if you don't want me to, I won't. It's your method and your script, after all!

**Comment by blawar** [comment]
You don't need to give me credit, you'll have to link them to this page to download--that is credit enough.  I look forward to reading your guide :)

**Comment by PsychOsmosis** [comment]
Hey, just wanted to inform you that I tried your fix with the latest commits and it worked flawlessly to remove-title-rights straight from the scene release NSP!! So now it's a few steps shorter to remove the title rights and delete the ticket!!

Thanks again!!

**Comment by PsychOsmosis** [comment]
By the way, I wrote up the tutorial today. Here's a link :
[https://gbatemp.net/threads/how-to-remove-fake-tickets-from-nsp-file-standard-crypto-equivalent-ban-risk-mitigation.518312/](url)

**Comment by PsychOsmosis** [comment]
Hello! How are you doing?

Some people on the forum that tried to apply the method for themselves are having issues that all the NSPs that were modified with nut to remove the rights and ticket can be installed but, when the game is launch, it comes up as "corrupted" and are prompted to redownload the game from the eShop.

After making sure nut was working correctly for them, I managed to pinpoint that the users affected are using ReiNX (one of them gets the issue even though he's updated ReiNX to the latest nightly). The console's firmware version doesn't matter, the problem occurs both on 5.1 and 6.0. I read on reddit that since about a month ago, ReiNX supposedly supports launching modified NSPs, so I don't understand why they get this error message.

Do you know anything about that? Is there a modified sysmodule they must install in order to make ReiNX compatible with the NSPs modified method?

If you don't know why the problem occurs, I will ask the ReiNX dev about it, since he's the most likely candidate to be able to do something about it considering it's a ReiNX compatibility issue.

Thank you very much!!
