### ISSUE TITLE
nut for network install and image scrape

### ISSUE THREAD

**Issue by darkarrow** [blawar/nut#109]
~~So first the network install, I added a game to a directory and nut is showing it when I start the server.py however in the tutorial it says to go to locations and add location in tinfoil however I do not see a locations in order to add this, there is a locations.conf but I do not know the syntax I would need to add it manually like that.~~

And then image scraping, in the readme is says to use command nut.py -s --scrape however when executing this I get the message "nut.py: error: unrecognized arguments: --scrape"

Thanks for any help with these, I have a feeling the first one is me just being stupid but idk I tried for a few hours doing things but to no avail so I turn to you.

**Comment by darkarrow** [comment]
I have figured out how to allow tinfoil to contact nut now so the first part of this problem is fixed but I still can't scrape images using the command supplied.

Also while I have the server.py running it constantly spits out "usb exception: No backend available", I'm not using usb for anything so I'm not sure what this error message is being produced for.

**Comment by throwawayay** [comment]
—scrape was removed in a early commit, those images are only used for the web interface and not an issue when using Tinfoil

Exception is due to missing libusb/winusb
