### ISSUE TITLE
XCI Support

### ISSUE THREAD

**Issue by RetroGamer74** [blawar/nut#11]
Hi, this is not an issue, it is a request, but as a programmer I consider it is very easy to add this feature if you want. I'm perfectly aware that XCI is only capable for SX OS, but many people owns.
XCI does not require installation as NSP, and the procedure is finished when you retrieve from the FTP Server the XCI file and you store it into one of the next folders:

/
/sxos/xci
/switch/xci

On any of that three folders SX OS is capable to find the XCI game. So the only job is RETR the file from FTP SERVER and store it into the root folder of microSD, or /switch/xci , or /sxos/xci.

That's all.

I hope you take it in care.

Thank you very much.

**Comment by ThatNerdyPikachu** [comment]
what

**Comment by blawar** [comment]
Are you asking for DZ to have the ability to download XCI files?  I was planning on adding support to install XCI with DZ (on the fly NSP conversion).

**Comment by RetroGamer74** [comment]
Hi, thanks for your answer. Yes I'm talking about DZ. Conversion in the fly would be great, but for people using SX OS, they can work with XCI directly. You only need to retrieve the XCI file and store it in the microSD root folder for example. You don't need do any installation or xci conversion.

**Comment by lavaJockey** [comment]
Just to let you know XCI files are gamecard dumps not eshop downloads. So this would be impossible unless it runs off of a custom server with XCI dumps.

**Comment by neFAST** [comment]
Is it a lot of work to enable xci download? If you guide me I'd like to work on a PR for this
