### ISSUE TITLE
Nut server with xci

### ISSUE THREAD

**Issue by yongbi85** [blawar/nut#111]
Hello,
I have a sx pro and i know you released sx server, however i run my nut server in a docker on my nas and you current nut server doesn’t offer xci integration.
Do you plan to release sx server also on github so it can be started on linux and not only under windows or add the xci integration on this nut server (without on the fly conversion, just like you did on sxserver)

**Comment by throwawayay** [comment]
you should be able to put xcis within the scan path, will show up

**Comment by yongbi85** [comment]
Should it be named xci or base in path ? Im lost there
