### ISSUE TITLE
NSZ Support

### ISSUE THREAD

**Issue by deathscreton** [blawar/nut#113]
Hey Blawar. I was wondering if you had read up on nsZip. It's a compressor for NSP files that got released awhile back and it works fairly well, but it's not supported much by anyone. Do you think you could see if it's something you'd be willing to add support for in NUT? It's be nice to have the benefit of saved space and inventory control. lol

Here's the git:
https://github.com/nicoboss/nsZip

Thanks for all you too bossman.

**Comment by meunierd** [comment]
I think the challenge here is that it would likely need to be re-implemented to be usable from Python in a portable manner. I say likely because the dotnet runtime's portable now and I'm sure someone's got a C# FFI working but that sounds like a huge hack.

**Comment by blawar** [comment]
adding a custom compression format soon
