### ISSUE TITLE
QNAP OS

### ISSUE THREAD

**Issue by eiros** [blawar/nut#117]
Is it possible to compile NUT for Qnap OS? It would be great to download games right on Qnap and install them to Switch directly from there.

**Comment by throwawayay** [comment]
Use container station and a python docker, YMMV

**Comment by eiros** [comment]
Thanks! I tried Docker - it is cool staff. But I have ARM CPU on my Qnap and I can't install pyqt5. Is it possible to make server.py without any interface features?

**Comment by station7** [comment]
Have you tried "python3 nut.py -S"? This works on my QNAP (at least for NUT < 2.0).

**Comment by eiros** [comment]
Thanks a lot!! "python3 nut.py -S" works great!
