### ISSUE TITLE
[Bug] Duplicate icons

### ISSUE THREAD

**Issue by c62624** [blawar/nut#12]
Using FTP.

Icons may appear twice in the grid view, where one game's icon overwrites a different game. Can occasionally be fixed by going to a different network folder in menu.

Example below shows a few games icons duplicated.

![2018093021065100-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/3870029/46265892-d5a39080-c4f8-11e8-9e43-82c1fd403a32.jpg)

**Comment by blawar** [comment]
should be fixed
