### ISSUE TITLE
Version 2.0 Web Site Does not Work

### ISSUE THREAD

**Issue by Viper911** [blawar/nut#122]
Just started using v2 (was working on older versions).  Scan is good, but when I go to the web site I just get errors on each refresh attempt and get no site displayed.

![image](https://user-images.githubusercontent.com/3239145/62620243-69df4080-b8de-11e9-9916-02458c1d6b37.png)

**Comment by Viper911** [comment]
If I throw http in front, the errors change to

![image](https://user-images.githubusercontent.com/3239145/62620328-aa3ebe80-b8de-11e9-8ac9-e05b99a47374.png)

**Comment by Viper911** [comment]
I updated my version of Python to 3.7.4 (was 3.7) and tried with IE to make sure Chrome wasn't caching something and now get.  Seems to start with a 401 error, then 404 on each refresh of the page.

![image](https://user-images.githubusercontent.com/3239145/62620856-f9392380-b8df-11e9-90d0-453458ab6f4d.png)

**Comment by Viper911** [comment]
BTW - went back to old EXE version and is working just fine.  Something is up with v2.0

**Comment by throwawayay** [comment]
No web server GUI in 2.0, it's just the api.
