### ISSUE TITLE
NUT 2.0: Linux version not finding/serving any files

### ISSUE THREAD

**Issue by station7** [blawar/nut#124]
The webinterface does not work on the windows and linux version, maybe this is intended. However, while nut.exe for windows serves the files in the scanned folder well, the linux version ("python3 nut.py -S") does not serve any files at all. I tried every possible path in nut.conf for the scan-folder, but sadly it does not even seem to find the files. I can see a connection " "POST /api/tinfoilSetInstalledApps/Xxxxxxxxxxx HTTP/1.1" 200 -, but the files do not show up in tinfoil.

I am happy to assist. Thanx for looking into this.

**Comment by Net-Felix** [comment]
do a
`wget -q --spider --user guest --password guest http://127.0.0.1:9000/api/scan`

**Comment by station7** [comment]
Initializing the scan with `wget -q --spider --user guest --password guest http://127.0.0.1:9000/api/scan` did the trick - thank you so much for helping me out.
