### ISSUE TITLE
File sizes not shown in Tinfoil

### ISSUE THREAD

**Issue by tantoinet** [blawar/nut#136]
Not sure if this fits into Tinfoil (4.10b) or Nuts (latest git clone), but when using both over USB, the file sizes aren't shown.
It would be great to show the free disk space among the total one (it looks like there is no way to show the total system memory and sdcard space in the switch).
Where can I leave Tinfoil related issues?

**Comment by Djf2884** [comment]
Nut work well and is able to detect file size, issue is with tinfoil (or lithium, same bug), when you install tinfoil and select the new games section, size is well displayed, but when u browse nut server from browse section, size is not displayed.

So not an issue with NUT server :)

**Comment by Sky2310** [comment]
Agree not a Nut Server problem. Besides, if you know what the size of the game is prior to installing why would you need to see it again anyway?

**Comment by throwawayay** [comment]
File sizes are shown when using the "New Games/DLC/Updates" section only, not in the File Browser section
