### ISSUE TITLE
v2.3 Windows executable - install over network fails

### ISSUE THREAD

**Issue by spyckotic** [blawar/nut#147]
nut 2.3 windows executable when installing XCI or NSP over the network with tinfoil 6.0 results in either "Failed to download the entire NCA, aborting" or "Failed to write place holder!  This is usually caused by not having enough available space on your SD card or NAND........."

USB install works as expected.

issue not occurring with network installs on v2.1

**Comment by fklfkl** [comment]
I'm also affected by this, tested on 2 different machines. Can narrow it down to the 'threaded response' changes from [this commit](https://github.com/blawar/nut/commit/0152a84438a1d169b516245ec7c354d22e051f80). As a temporary fix you can reverse those changes and you should be good to go

**Comment by CorgiZack** [comment]
I've also been seeing this issue, on either the exe or the py. Reverted to 2.2C and having no issues there.

**Comment by Sky2310** [comment]
Install the latest Windows 10 cumulative update.

**Comment by CorgiZack** [comment]
> Install the latest Windows 10 cumulative update.

I did this, and the outcome is the same. Aligns better with the threaded response changes mentioned above.

**Comment by chrism37** [comment]
Same Issue here, using on latest version of Windows 10, USB works fine. I will try it on a 2019 server later on to see if it still happens.

**Comment by throwawayay** [comment]
Should be resolved by https://github.com/blawar/nut/tree/v2.4
Reopen if needed
