### ISSUE TITLE
Scroll bar very hard to see when using Dark theme. White theme is fine.

### ISSUE THREAD

**Issue by c62624** [blawar/nut#15]
Title

![2018093020530500-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/3870029/46265863-a2f99800-c4f8-11e8-9969-d2ef1cb276a8.jpg)

**Comment by blawar** [comment]
do you want more padding between the scroll bar and the icons?

**Comment by x43x61x69** [comment]
I think the highlighting text color make it hard to read also, consider the font size of the list view.

**Comment by ThatNerdyPikachu** [comment]
Yeah, this seems to be a issue for me as well.
