### ISSUE TITLE
NUT as Service under Linux

### ISSUE THREAD

**Issue by numerunix** [blawar/nut#151]
Hello,
i have a linux box running debian buster, and i made two files for run nut as system daemon.
I want to share it because i think it should be useful to other users.

First file in zip (nut.service) run nut on usb using root access, second file (nut-wifi.service) run it as http server.

The only change in two files is the running command (ExecStart under service) and you know better than me the parameters that must be given.

The who files must be put in /lib/systemd/system, with nut in the /opt/nut-2.2C directory, but the start directory can be changed changing ExecStart line.

The access can be reduced adding two lines (User=USER and Group=GROUP) in the ExecStart sections changing USER and GROUP with relative user and group that should be used.

Reducing priviledges can be useful with wifi, but if you want to run USB with reduced priviledges, you have to configure  udev creating the file /etc/udev/rules.d/99-switch.rules with the following line:

SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3000", GROUP="plugdev"

Making this you say to udev that every user in the group plugdev can access to switch.

There are no particular configuration for wifi.
For running nut as system, after having putted the files in /lib/systemd/system you have to run systemctl start nut(-wifi)(.service) in shell, it will automatically ask for root password.

For stopping service you have to use systemctl stop nut(-wifi)(.service).

Have a good day.

[nut.zip](https://github.com/blawar/nut/files/3838260/nut.zip)

**Comment by throwawayay** [comment]
You are welcome to make a PR to the repo to add a nut.service.
Thank you for your contribution.
