### ISSUE TITLE
Browsing directories and in-app folders

### ISSUE THREAD

**Issue by Sky2310** [blawar/nut#152]
The app works great but the feature to browse folders containing game files currently does not work. That is, the exe file needs to be placed inside the folder container files or the user must copy & paste the folder location manually instead of clicking on browse and doing so from within the app itself. 

Also, the app does not like game files that are in folders combined with game files that are not in folders. For example, I have around 20 NSP files that are not in folders and another 30 in folders and the app would not detect those in folders.

Thank you for your great work.

**Comment by throwawayay** [comment]
Reorganize them with an old version of nut or with NSCB.
GUI bug is likely due to PyQt, PRs are welcome to attempt to fix it.
