### ISSUE TITLE
Error opening drive folder

### ISSUE THREAD

**Issue by pabermod** [blawar/nut#153]
I have an error opening a drive folder (I have removed my teamdriveId)
<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?pageSize=100&teamDriveId=#############&includeItemsFromAllDrives=true&corpora=teamDrive&supportsTeamDrives=true&q=%27None%27+in+parents+and+trashed%3Dfalse&fields=nextPageToken%2C+files%28id%2C+name%2C+size%2C+mimeType%29&alt=json returned "File not found: .">
begin recv

**Comment by x1d0** [comment]
I have exactly the same problem
Its only when using gdrive with nutfs, direct gdrive work perfectly
nuts 2.2c still works
I prefer using gdrive over nutfs sometimes I can get 50mb/sec with wired network

routing to getDirectoryList
route exception: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?pageSize=100&teamDriveId=[###]&includeItemsFromAllDrives=true&corpora=teamDrive&supportsTeamDrives=true&q=%27None%27+in+parents+and+trashed%3Dfalse&fields=nextPageToken%2C+files%28id%2C+name%2C+size%2C+mimeType%29&alt=json returned "File not found: .">
192.168.20.34 - - [18/Nov/2019 19:45:55] "GET /api/directoryList/gdrive/hbg1/hbg/NSZ/base HTTP/1.1" 404 -

**Comment by pabermod** [comment]
@x1d0 how do you configure direct gdrive?

**Comment by x1d0** [comment]
@pabermod Just add a gdrive repository in tinfoil directly and since nuts already copied credentials.json in your switch it will work right away

**Comment by blawar** [comment]
I cannot reproduce, however I can try to guess, do any of your folder names have a space or any special characters in them?

**Comment by x1d0** [comment]
No space or special character (lots of spaces and special characters in files)

/api/directoryList/gdrive/hbg1/hbg/NSZ/base

But my windows locale are in Canadian French maybe this is affecting nuts and that explain why direct grive connection is working

I will try soon

**Comment by x1d0** [comment]
Just tested on my freshly formatted computer and on my Windows server 2019 dedicated server and I have the same problem only on 2.4

gdrive over nutfs if giving error 404 on the "stash" its clear some files have problematic name (folders have no space or special characters)

I really don't know why

**Comment by pabermod** [comment]
Still happening with latest nut and tinfoil

**Comment by introkun** [comment]
@pabermod what about now? Please specify tinfoil version, protocol (nut/nutfs/etc) and OS of your server.

**Comment by pabermod** [comment]
I do not longer have a gdrive account with backups so I cannot try, sorry

**Comment by introkun** [comment]
@x1d0 what about you?

**Comment by x1d0** [comment]
> @x1d0 what about you?
Sorry for the late reply I had to setup my switch to test this

I used the latest commit on your nuts fork its working perfecty now and its also quite fast with my wired network switch adaptor

**Comment by introkun** [comment]
Good to hear that @x1d0
