### ISSUE TITLE
usbfs issues with specific folder or filename characters

### ISSUE THREAD

**Issue by mchubby** [blawar/nut#155]
# problem 1
### Background

The pound/sharp sign `#` is problematic for folders.

### Your environment

* version: nut.exe v2.4
* operating system: Windows 10 x64 French, 1809
* any other relevant environment details: Lithium console-side

### Steps to reproduce

1. Create a folder with a `#`. Example: `T:\hello#1`
2. Run nut.exe
3. On the switch homebrew application, Browse to the usbfs drive
4. Attempt to enter the hello#1 folder

### Expected behaviour

Shows folder content

### Actual behaviour

- app lists the folder as `hello`. 
- entering the folder locks up the app (home button returns to HOS)
- server-side, a console error appears: 
```
url /api/directoryList/T/hello
routing to getDirectoryList
route exception: [WinError 3] The system cannot find the path specified: 'T:\\hello'
begin recv
```
(nut.exe remains active and hasn't crashed)

Note: for folders **starting** with a `#` character, the name is displayed wrong, duplicated in the app (e.g. #foo becomes #foo#foo)

# problem 2
### Background

The semi-colon `;` is problematic for NSP files.

### Your environment

* version: nut.exe v2.4
* operating system: Windows 10 x64 French, 1809
* any other relevant environment details: Lithium console-side

### Steps to reproduce

1. Rename NSP to name with a `;`. Example: `T:\a;bc.nsp`
2. Run nut.exe
3. On the switch homebrew application, Browse to the usbfs drive
4. Attempt to install this package

### Expected behaviour

Shows NSP info

### Actual behaviour

- Error Message: "Failed to open NSP"
- No error server-side
```
url api/fileSize/T/a;bc.nsp
routing to getFileSize
usbresponse write
sending 102 bytes
```

Note: the semicolon `;` is also bad for folder names

**Comment by spikeyxx** [comment]
I am having a similar problem with 8.10 Tinfoil and most recent NUT.

Sometimes Folders open and allow install with USBFS, sometimes they do not - It is not consistent.

Installing, sometimes the Install Fails and the App locks up requiring a reboot. 

I'm not 100% sure but this may be responsible for a resent Emunand corruption I had. - It may be unrelated, I RMA'd that specific Micro SD card and received a new one.

**Comment by introkun** [comment]
@mchubby please try NUT version from the master branch and let us know

**Comment by mchubby** [comment]
OK @introkun I took the time to create a venv, pip install the requirements from master

File list still does not show up on the switch.
```
Scanning NSPs on the filesystem
A:\#1 HDD21+NSW%extracted
Sun Nov  8 12:32:30 2020 Server Starts - 0.0.0.0:9000
Saving NSPs to the configuration file
USB Connected
begin recv
read complete
receiving 10 bytes
url /api/queue
routing to getQueue
usbresponse write
sending 3 bytes
begin recv
read complete
receiving 12 bytes
url /api/search?
routing to getSearch
Scanning NSPs on the filesystem
A:\#1 HDD21+NSW%extracted
Saving NSPs to the configuration file
usbresponse write
sending 473 bytes
begin recv
read complete
receiving 19 bytes
url /api/directoryList/
routing to getDirectoryList
usbresponse write
sending 238 bytes
begin recv
read complete
receiving 20 bytes
url /api/directoryList/A
routing to getDirectoryList
usbresponse write
sending 1011 bytes
begin recv
read complete
receiving 43 bytes
url /api/directoryList/A/#1 HDD21+NSW%extracted
routing to getDirectoryList
usbresponse write
sending 1011 bytes
```

**Comment by blawar** [comment]
The # character has special meaning to tinfoil.  In general, you should never use special characters like that in file names / directory when the file is to be accessed by different file systems.

It’s not working for you because of the # character in your directory name @mchubby

**Comment by mchubby** [comment]
So... WONTFIX I guess?

**Comment by blawar** [comment]
Correct, this is a WONTFIX and its a Tinfoil issue not a nut issue.  Just rename your directory to not contain a # character.
