### ISSUE TITLE
USB installation VERY slow

### ISSUE THREAD

**Issue by knerlington** [blawar/nut#156]
Using a USB-C to USB-C cable from my computer via Thunderbolt 3 or USB-A to USB-C from USB2 or USB3 ports gives me about 1MB/s transfer speed. Am I missing something? My MicroSDXC card is a 128GB Sandisk Ultra Class 10 UHS-1 so I should have a minimum of 10MB/s transfer rate. While this process using NUT installs a game I understand it's different, but 1MB/s or lower feels very wrong. Cable is rated at 480Mbit/s (60MB/s)

SD card is formatted as FAT32. Running CFW on a emuMMC partition.

EDIT:
This is actually (or at least with high probability) down to the actual SD card itself. Bought a 128GB UHS-3 (or 2) card and that install between 30-50MB/s over USB. So this might not be a bug and the issue can be closed.

**Comment by knerlington** [comment]
While installing I can't navigate Tinfoil at all. Should this be reported here or at the Tinfoil github?

**Comment by blawar** [comment]
are wifi speeds about 10 MB?

**Comment by ericdude4** [comment]
I am also getting very slow performance over usb-c to usb-c (2018 MBP 15) when trying to install NSZ files.

**Comment by knerlington** [comment]
> 
> 
> I am also getting very slow performance over usb-c to usb-c (2018 MBP 15) when trying to install NSZ files. Average speed 750 KB/s to 2 MB/s

This is actually (or at least with high probability) down to the actual SD card itself. Bought a 128GB UHS-III (or 2) card and that install between 30-50MB/s over USB.
