### ISSUE TITLE
[Feature] Ignore hidden files in scan folder

### ISSUE THREAD

**Issue by V33m** [blawar/nut#158]
Everything is working fine on macOS Catalina 10.15.1, however, I've some feature suggestions and tips you can add to README concerning using nut on MacOS.

First, it would be beneficial to not include hidden files in the scan folder such as `._filename`. In my case, I've twice the number of files because of the `._counterpart` macOS creates. It should be of relevance for Linux too.

Further, I received the error `usb exception: No backend available` in the beginning. I tried to install libusb in addition with `pip3 install libusb`, yet it didn't fix it. However, by installing libusb through [Homebrew](https://brew.sh/) with `brew install libusb`, the problem was solved. Someone else might find this tip useful if they want to run nut on OSX/Linux.

**Comment by introkun** [comment]
As far as I see it only scans files with specific extensions (nsp/nsz...). Is it still actual @V33m ?

**Comment by V33m** [comment]
Yes, I guess so if it only scans files with specific extensions. Here is an example of a scenario of files where  you have the counterpart files which store file information related to extended attribute on HFS+ or Unix/UFS volumes:
```
._FILE1.nsp
FILE1.nsp
._FILE2.nsz
FILE2.nsz
```
Preferably filenames starting with `.` or `._` should be ignored as well.

**Comment by introkun** [comment]
Confirmed issue 
![NUT USB : Web Server v2 7 2020-10-31 00-38-32](https://user-images.githubusercontent.com/61635/97759221-a31e5480-1b11-11eb-8e6f-270a2362309f.png)

**Comment by introkun** [comment]
More fixed for the issue #202
