### ISSUE TITLE
https support in dz?

### ISSUE THREAD

**Issue by tonyzzz321** [blawar/nut#16]
Are you planning to add https support in dz? Maybe just use a version of curl with https support?

**Comment by blawar** [comment]
Technically DZ tries to use it, but its not working with the curl devkitpro provides.  You should consider submitting a bug to them to fix it.  I may do a custom compile of curl for it, but https isnt really something that is in high demand I would THINK.

**Comment by gjimenezf** [comment]
I too support this. 
There are multiple cloud repositories that only support https and not http, form example google drive

**Comment by blawar** [comment]
I will add it, I have to custom compile libcurl for it.

**Comment by blawar** [comment]
added

**Comment by gjimenezf** [comment]
Did you used a bodge or did you really fix it the right way? 
Devkitpro is struggling to solve this you can help them if you already did:
https://github.com/devkitPro/pacman-packages/issues/50

**Comment by blawar** [comment]
@gjimenezf i sent SSL patches to devkitpro, they are not interested.  https is solved in DZ / Tinfoil.
