### ISSUE TITLE
NSP download exception [errno 13]

### ISSUE THREAD

**Issue by MyChoco17** [blawar/nut#162]
downloading the NSP for BOTW (i bought the game but i got banned and my sd card was full so i formatted (after making a backup)) and it won't let me reinstall.
![poopyyyyyyyyy](https://user-images.githubusercontent.com/58914302/70866514-9da03600-1f62-11ea-967d-542dc032c65a.png)
![poopyyyyyyyyy x2](https://user-images.githubusercontent.com/58914302/70866515-a133bd00-1f62-11ea-9f21-97ed9bd5345e.png)

**Comment by throwawayay** [comment]
Remove the ticket and reinstall
