### ISSUE TITLE
After scan a new folder, the item list been added but not purge then add

### ISSUE THREAD

**Issue by skygunner** [blawar/nut#164]
This might cause issue when the old folder contains hundreds or thousands items, then you switch to a sub folder with only 3 items. After scan been clicked, the new 3 items been added to the list, but the list is still showing and providing the old 1000 items. Making it very hard to find and select the new 3 items on the installer. 

I'd suggest the scan function to purge the old listing and only add the items presented in the new folder only.  Or give a button to hide the old items.

**Comment by deadair3210** [comment]
This would be appreciated. Would make testing files much easier

**Comment by introkun** [comment]
It is very similar to the issue #192 . Must be fixed by my PR https://github.com/blawar/nut/pull/193

**Comment by introkun** [comment]
Ah no.. it only fixes removal of files at the filesystem, not the change of the scanned folder.

**Comment by introkun** [comment]
I've fixed it in my PR.
