### ISSUE TITLE
NUT + Tinfoil 7 USB installation, NUT is sending the wrong file

### ISSUE THREAD

**Issue by skygunner** [blawar/nut#165]
**Nut 2.5**

**Folder A**
CONTRA ROGUE CORPS [0100F2600D710000] [v65536] (1G+1U+5D)[rr].nsp
**Folder B**
Contra Rogue Corps [0100F2600D710000][v0].nsp

Scan folder A:
try install the nsp. failed due to garbage file. 

Scan folder B:
try install the other .nsp in folder B, Nut is still sending the previous nsp file in Folder A. 

Both Nut status bar and terminal is showing sending the file in folder A. Installation sure will be fail. 

(**Another issue after this:**
restart Nut and without reconnecting the USB, without restart Tinfoil, try to install the .nsp in folder B will not start. Try install other nsp does work. 
)

Even restart Nut and Tinfoil 7, try install the nsp in folder B, Nut will still send the nsp in file A. 
It seems, when two roms existing in Nut's list (database), it is searching for a matching title ID and version file in the list by order and send the first one that matches, it is not sending the actual one that the user has selected in Tinfoil.  When the file in Folder A been deleted, Nut will send the right selected file in folder B.

This is also related to issue https://github.com/blawar/nut/issues/164

**Comment by mchubby** [comment]
Tagging related to #155 

`+` in a URL is the escape code for a 'space' character. I suppose if you try renaming the file beforehand it might work better

**Comment by introkun** [comment]
@skygunner may I ask you please to try version from the master branch?

**Comment by introkun** [comment]
Issue #164 is resolved

**Comment by introkun** [comment]
https://github.com/blawar/nut/issues/175#issuecomment-721981394

**Comment by introkun** [comment]
Closed due to inactivity
