### ISSUE TITLE
NUT appearing USB connected but not showing games on Tinfoil

### ISSUE THREAD

**Issue by yuditofu** [blawar/nut#166]
i have already installed the tinfoil driver and inside the NUT window all games are showing and it says USB connected but i can install nor find any games at the file browser. inside the folder is blank. How can i solve this problem?

**Comment by squallscloud** [comment]
Also have this problem, will try updating everything to see if it resolves itself.

**Comment by jacaTM** [comment]
Also happening to me, all updated

**Comment by howtobanana** [comment]
Also same problem for me!

**Comment by introkun** [comment]
@howtobanana please provide Tinfoil version, Nut version, log of the nut console.

**Comment by introkun** [comment]
Closed due to inactivity

**Comment by Roo7z** [comment]
i tried nut v3.1 and v2.7
tinfoil has version 11.00 v9
installed the libusbK-3.0.7.0 driver with zadig 2.5 for "Nintendo Switch", "Tinfoil (Interface 0)" and "Tinfoil (Interface 1)"
still i cant see the .xci file when i go to file browser > usbfs:/ in tinfoil.
at some point i saw my .xci file in the XCI tinfoil menu but when i tried to install it i had an error saying "unknown nca magic decryption failed"
nuts via network as described in the tinfoil help section doesn't work either.
pls help
