### ISSUE TITLE
Enhancement: Update file list on access

### ISSUE THREAD

**Issue by Strat00s** [blawar/nut#169]
I have the nut server running 24/7 on my server and making it possible to update the file list when I access the server from the switch would be amazing. Now I always have to restart the nut server for it to reload the files. Is it possible to either automate it on file change or update the file list on connection?
Thanks.

**Comment by kayjaybees** [comment]
+1
Background scanning would be amazing

**Comment by dexterwick** [comment]
+1

**Comment by Ronald-Diemicke** [comment]
+1

**Comment by Gardosen** [comment]
+1

**Comment by dalkain** [comment]
+1

**Comment by introkun** [comment]
@Strat00s please check my changes. It should work now for you.
