### ISSUE TITLE
FTP/HTTP: "Couldn't resolve host" in dz

### ISSUE THREAD

**Issue by ErAzOr2k** [blawar/nut#17]
Hi,

I try to access an external HTTP or FTP ressource over WAN via domain name. But I just get: Couldn't resolve host. 
From my browser everything is fine.

Is there anything I can do?

Update: FTP is also affected by this issue. Connecting over IP is working fine.

**Comment by morrison22** [comment]
If I am not mistaken, DZ does not currently support resolving hostnames.
I have not tested this, however, you may give this a try for a possible workaround:
1) Visit https://whatismyipaddress.com/hostname-ip and type the hostname of the external HTTP server in the Lookup field.
2) Click the button marked "Lookup IP Address" to obtain the corresponding IP address.
3) Configure "locations.conf" to use the obtained IP address in place of the host name. 
Note: Don't forget to add a trialing / at the end of the URL.

**Comment by blawar** [comment]
Hey, this is a bug in devkitpro.  I will add a work-around-hack for it temporarily.
