### ISSUE TITLE
problem with nut + tinfoil

### ISSUE THREAD

**Issue by XiNaru** [blawar/nut#170]
i cant connect with nut.exe if i use tinfoil
the drivers are installed.

and now, if i started nut.exe

invalid magic! b'\xc1\x16[+'
failed to read!

i dont know why this come

**Comment by throwawayay** [comment]
Update TInfoil and check that your files are valid

**Comment by XiNaru** [comment]
1. Please give us the opportunity to answer before you close a topic. just saying something and then closing it straight away is more than rude.

2. I ALWAYS use the latest version of programs. also from nut and tinfoil. the problem is by no means with the version.

**Comment by throwawayay** [comment]
Verify your file is not corrupt.
Use https://github.com/julesontheroad/NSC_BUILDER or similar.
