### ISSUE TITLE
gdrive cache of files/directories list in tinfoil + searchable list

### ISSUE THREAD

**Issue by khalilgharbaoui** [blawar/nut#173]
The gdrive config was and is ok most of the time... 
sometimes it acts up but after restart of tinfoil it works again.
You need to make a cache for the files/directories list from gdrive because loading it each time takes way too long.
Also searching within that list would help a lot.

**Comment by yongbi85** [comment]
I second this request
A cache for gdrive would be nice and also the abilitu to search in all file browse entry actually (basic windows type search on file name)

**Comment by introkun** [comment]
Very similar to issue #182

**Comment by khalilgharbaoui** [comment]
This https://github.com/blawar/nut/issues/182#issuecomment-721508087 might indeed make sense.
