### ISSUE TITLE
Daemon execution?

### ISSUE THREAD

**Issue by plato79** [blawar/nut#176]
Is it possible to make the network server mode executed as daemon? We could add a "-d" option to make it so and log the output to a logfile with a "-l" option..

I'll also try to look for it but if you have enough know how to make this, could you make it?

**Comment by Gardosen** [comment]
https://stackoverflow.com/questions/1423345/can-i-run-a-python-script-as-a-service

running it as a deamon could be implemented, but the question is how helpful this could be. 

for now, you could use an easy workarround and use a software like screen or tmux (that's what i use)
then just start nut inside a tmux session, and detach from it. if you wanna go back to nut, hook back into the tmux session.

**Comment by introkun** [comment]
You can solve it by using a 'screen' Linux command.

**Comment by plato79** [comment]
Yeah, I know that's a solution and I used to do that earlier.. Though someone mentioned supervisord and that worked for what I really needed.. Because I wanted to restart it based on a cron job and supervisord is much better for that. Thought it would have been better if it had itself a daemon support.

**Comment by throwawayay** [comment]
doge does this technically, and I believe all the APIs have been re-added to make it happen via REST calls.
If you need un-minified doge source to look at this further let me know.
