### ISSUE TITLE
Folders spacing problem 

### ISSUE THREAD

**Issue by Vegeta780** [blawar/nut#180]
hi Nut working fine installing and others, i have a problem with folders opening when i open a folder with space name my tinfoil freeze  ()
am using tinfoil 8.0 nut latest 
[https://i.ibb.co/PctdNcw/Screenshot-7.png](url)
sorry for bad english

**Comment by introkun** [comment]
@Vegeta780 could you please provide me steps to reproduce the issue? Are you using tinfoil? What are the steps?

**Comment by introkun** [comment]
@Vegeta780 any news?

**Comment by introkun** [comment]
Closed due to inactivity
