### ISSUE TITLE
Google Drive Cache + Index File

### ISSUE THREAD

**Issue by eXhumer** [blawar/nut#182]

**Comment by introkun** [comment]
@eXhumer could you please add more details?

**Comment by throwawayay** [comment]
Sounds like an integration/mashup that can utilize some code from https://github.com/eXhumer/TinGen

e.g. natively allowing nut to read from Google Drive for installs

**Comment by borntohonk** [comment]
@introkun 
1. Add a tab in gui elements to save bits of the command(s) required to call an indexer either externally or integrate it into nut itself. Similar to how you can save paths for the organize feature.
2. Add a button similar to the gdrive-auth button nut has that uses the configured information from step 1, to index the team drive/gdrive folder of your choice.


example inexers
rust: https://github.com/DevYukine/rustfoil
python3: https://github.com/ii0606226/TinGen
nodejs: https://github.com/BigBrainAFK/tinfoil_gdrive_generator

**Comment by throwawayay** [comment]
Merged from https://github.com/blawar/nut/issues/173

**Comment by blawar** [comment]
It already is cached.  The cache is only good for about 4 hours though.

**Comment by introkun** [comment]
Closed per https://github.com/blawar/nut/issues/182#issuecomment-734921812
