### ISSUE TITLE
Mac OS Instructions?

### ISSUE THREAD

**Issue by switch64** [blawar/nut#183]
I only have access to Mac OS. When I follow the guide, it tells me to edit "/etc/udev/rules.d/99-switch.rules". udev is not a folder in etc. Should I edit "/etc/" ?
Also, pip3 can't find the package "googleapiclient". I can't find it in pypi either.
Sorry if these are dumb questions.

**Comment by Nandox7** [comment]
Make sure you have the latest code.
Just installed it in OSX 10.15, only issue I had is that I had to use the a VirtualEnv and amend a typo in the requirements.txt but I'll submit a PR soon.

**Comment by comigor** [comment]
@Nandox7 when running on macOS, what path did you configure on tinfoil?

**Comment by switch64** [comment]
@comigor I don't understand what you mean by path on tinfoil, haven't touched tinfoil yet. I got nut to run once I installed google-api-python-client and google-auth-oauthlib. I'll try to install a homebrew nsp later. Thanks for the help @Nandox7.

**Comment by Nandox7** [comment]
@comigor if you mean the scan path I used the downloads folder of my mac but that all depends where you placing your downloaded files.

**Comment by pparrilla** [comment]
I don't have /etc/udev.... directory, so i can't add the rule. When i run python3 nut.py, the windows is open but the shell show `usb exception: No backend available`. What should i do?

**Comment by cacamaca** [comment]
For those that are experiencing similar issues I have on macOS Catalina, here is what worked for me:

1. Install Python 3 - 'brew' command requires Homebrew to be installed
    brew install python3

2. Install Pillow
    This one has been tedious to figure out but in the end the following worked to get around the 'zlib module is missing' error:
        brew install libtiff libjpeg webp little-cms2 
        pip3 install Pillow 
    
3. Install dependencies using pip3:
    pip3 install google-api-python-client   
    pip3 install google_auth_oauthlib  
    pip3 install PyQt5 
    and any other modules that are being displayed as being missing - there are quite a number of them

Hope that helps.

**Comment by switch64** [comment]
@pparrilla forget that step. don't do anything to your /etc/ dir.
brew install python3 doesn't work for me, I just installed it the normal way. What worked for me is (after a fresh install of python 3.9):

1. Install Python 3 and libusb - 'brew' command requires Homebrew (brew.sh) to be installed.
Download python 3.9 from [python.org](https://www.python.org/downloads) (or just get 3.9.0 [here](https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg)) and follow its instructions to install.
`brew install libusb`

2. Install pillow (@cacamaca I didn't need any dependencies. I only had to install it seperatly). 
`pip3 install Pillow`

3. install dependencies 
`pip3 install -r {nut-master folder}/requirements.txt`
`pip3 install google-api-python-client google-auth-oauthlib`

4. run the program (you need to do this every time you want to open NUT)
`python3 {nut-master folder}/nut.py`

Thanks to everyone that helped.
