### ISSUE TITLE
Error binascii.Error: Invalid base64-encoded string

### ISSUE THREAD

**Issue by KoRnEr007** [blawar/nut#186]
Hello,
i see my games on tinfoil, but when i try to launch a NSP or XCI, i have this error:
binascii.Error: Invalid base64-encoded string: number of data characters (197) cannot be 1 more than a multiple of 4

And the error is 'failed to open NSP'
Do you know this issue ?
I launch nut.exe on windows 10

**Comment by Baldwin90** [comment]
What was the issue? I'm having the same problem
