### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hungtr97** [blawar/nut#190]
Hi,

Im connecting via wifi, when try to install nsp, it show this error and "Failed to open NSP" on switch.
NUT server run on RaspPiOS-Debian (Raspberry pi), Python 3.7.3
any info needed pls ask, thanks.

----------------------------------------
Exception happened during processing of request from ('192.168.12.124', 58144)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/nut-2.7/Server/__init__.py", line 254, in __init__
    super(NutHandler, self).__init__(*args)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/home/pi/nut-2.7/Server/__init__.py", line 303, in do_GET
    self.do('get')
  File "/home/pi/nut-2.7/Server/__init__.py", line 289, in do
    id, password = base64.b64decode(self.headers['Authorization'].split(' ')[1]).decode().split(':')
  File "/usr/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
----------------------------------------

**Comment by Tobiti** [comment]
I have the same problem with the newest tinfoil version and the latest windows release

**Comment by v0armd9** [comment]
Same issue here.
Also, usb always shows as disconnected, so I can't even use that as a backup

**Comment by introkun** [comment]
Could you please double check your login and password you use in tinfoil.

**Comment by Tobiti** [comment]
I checked them and both are right

**Comment by introkun** [comment]
Can you test please on the latest version in master branch?

**Comment by hungtr97** [comment]
Yes, the login and pass are guest guest.
I user both master and v2.7, and they have the same error.

**Comment by hungtr97** [comment]
btw, i had do some debug,
in file Server/__init__.py, line 289, self.headers['Authorization']
return "Basic Z3Vlc3Q6Z3Vlc3Q=" when i do getDirectoryList,
but when i download file, it return "Bearer ya29.c.KpwB4gc7VdssnEclCMZZBPPSfj25voh29BXDu_gevOlfszjt_0_kUzXZ6uT70PhAKFBkvN22S7M8tj0F8HbEeYX5A8ksnCDTNqszh2-9RUeUtZgLbzxUbSvjDPc1iS9_e9s7aLMjGcr3lZNgfo2jOxTc1C43W_PQ8LjGJcXFTDHHxhfs7bXcJd7Hs6QOk3VXTl3RwqcNPoq4ojAG9e8x"
Is this normal?

And if i hard code this, i can download file now,
foo = "Z3Vlc3Q6Z3Vlc3Q="
id, password = base64.b64decode(foo).decode().split(':')

**Comment by introkun** [comment]
Arr you using tinfoil? Not sure when getDirectoryList called.

**Comment by hungtr97** [comment]
Yes, im using tinfoil.
getDirectoryList is called when im browsing in nutfs mode, in nut mode it doesnt work.

**Comment by introkun** [comment]
So now it looks like tinfoil issue since base64 password is received in some strange format, thus not decoded by nut server...

**Comment by introkun** [comment]
Why nut protocol doesn't work for you?

**Comment by hungtr97** [comment]
idk, both show the same error.

**Comment by hungtr97** [comment]
if i do hardcoding 
id, password = 'guest', 'guest'
then it will work.

**Comment by introkun** [comment]
> if i do hardcoding
> id, password = 'guest', 'guest'
> then it will work.

Could you please provide exact steps to reproduce the issue?

**Comment by introkun** [comment]
Cannot reproduce the issue on tinfoil 3.0.2 and nutfs protocol.

**Comment by introkun** [comment]
Cannot reproduce the issue on tinfoil 8.10 and nutfs protocol.

**Comment by hungtr97** [comment]
I'm using tinfoil 8.0, NUT server install on Debian(raspberry pi).
Tinfoil connect to NUT via Wifi.
add new File Brower with
> Protocol: nut
Host: (nut server ip)
Port: 9000
Username: guest
Pass: guest

Save and open.
Open to download > tinfoil show error: 
`Failed to open NSP`

on NUT server show error:
```
File "/home/pi/nut-2.7/Server/init.py", line 289, in do
id, password = base64.b64decode(self.headers['Authorization'].split(' ')[1]).decode().split(':')
File "/usr/lib/python3.7/base64.py", line 87, in b64decode
return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by blawar** [comment]
Try disabling jits or any other remote locations.  Extra headers being sent are caused by those.

**Comment by shinseiryu** [comment]
Was also getting "binascii.Error: Incorrect padding". Removing the other locations in Tinfoil as blawar says fixed it for me.

**Comment by introkun** [comment]
@hungtr97 is workaround works for you?

**Comment by hungtr97** [comment]
Remove remote location not work for me,
But hardcode id, password does.

**Comment by introkun** [comment]
@hungtr97 please be careful, you're exposing your nut server without authorization (since it's hard-coded)...

**Comment by hungtr97** [comment]
@introkun yes, im fully aware of that, just use it local and block port on NAT firewall

**Comment by introkun** [comment]
@hungtr97 what's your version of raspberry? I have one so I can try it.

**Comment by hungtr97** [comment]
It's model 3 B+ with raspberry pi os(debian).

**Comment by introkun** [comment]
Works on master on Raspberry Pi 3 Model B Rev 1.2

**Comment by introkun** [comment]
@hungtr97 can you please try on master branch version?

**Comment by introkun** [comment]
Closed due to inactivity
