### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 2: invalid start byte

### ISSUE THREAD

**Issue by heseifert** [blawar/nut#191]
Hi,
i get an error on latest Tinfoil and Windows patch installation.
I use the nut network install feature with default username and password.

![grafik](https://user-images.githubusercontent.com/9132452/97083532-050e2400-1611-11eb-9c03-c77edc4ecaed.png)

**Comment by introkun** [comment]
Can't reproduce on the latest version in master at MacOS (Python 2.8.6).

**Comment by janoxakes** [comment]
Same problem on Linux. 'Solved' by hardcoding the user and password in lines 317 and 289 of server/__init__.py as follows:
`            id, password = 'guest', 'guest'`

**Comment by introkun** [comment]
@heseifert are you still experiencing the issue?

**Comment by introkun** [comment]
Closed due to inactivity
