### ISSUE TITLE
Add console-only version?

### ISSUE THREAD

**Issue by 1DontEx1st** [blawar/nut#197]
I'm only running headless linux containers so was wondering if there's a way to remove the GUI requirement.

**Comment by introkun** [comment]
You can run nut.py without UI.

**Comment by throwawayay** [comment]
`nut.py --server` should do the trick

Possibly related: https://github.com/blawar/nut/issues/151

**Comment by introkun** [comment]
@throwawayay it's possible about Qt in requirements.txt file.

**Comment by 1DontEx1st** [comment]
Sorry, obviously I was ignorant of the "server" parameter. Thanks!
