### ISSUE TITLE
keys.txt vs Keys.txt

### ISSUE THREAD

**Issue by bad1dea** [blawar/nut#2]
FYI,

CDNSP is looking for keys.txt in the cmdLine, vs Keys lib looking for Keys.txt, so unless you have both its kind of screwy :)

I know you're developing really quickly, might have missed it, loving the progress so far.

**Comment by blawar** [comment]
I fixed this in the latest commit.  It wasnt a high priority since the files were going to be renamed anyway :)

**Comment by blawar** [comment]
Actually, I thought you were talking about titlekeys.txt and CDNSP downloading the titles as unknown.  After I closed the issue, I realized what you were saying.  Its late, i changed Keys.py to look for keys.txt all lower case, for you non-windows users :)

**Comment by bad1dea** [comment]
Perfect, loving the progress.
