### ISSUE TITLE
Hidden files are listed in filebrowser mode

### ISSUE THREAD

**Issue by introkun** [blawar/nut#202]
### Steps:
- create a hidden file in nsps folder (e.g. ".hidden.nsp")
- connect to server from tinfoil via filebrowser mode

### Result:
File ".hidden.nsp" is listed in the tinfoil

### Expected result:
File ".hidden.nsp" is not listed in the tinfoil

**Comment by introkun** [comment]
Some code is written in issue #201

**Comment by throwawayay** [comment]
Implemented with `is_file_hidden`, seems complete
