### ISSUE TITLE
Main thread in console continues to run after GUI is closed

### ISSUE THREAD

**Issue by introkun** [blawar/nut#203]

**Comment by introkun** [comment]
Latest nut from master branch (sha: 62f7864)

**Comment by introkun** [comment]
this is so annoying :(

**Comment by blawar** [comment]
This bug only exists when using nut_gui.py, python threads have to gracefully exit.  i'm not sure if its a problem with qt not being shut down correctly or if its one of the threads nut is creating, I will take a look as well.  I always assume it was something not being done correctly with QT.

**Comment by throwawayay** [comment]
https://github.com/blawar/nut/commit/c9cd428f9c072b6ccc8cc5d88c487274c327c5f2
