### ISSUE TITLE
USB connection not working

### ISSUE THREAD

**Issue by AzukaChan** [blawar/nut#206]
Hi there,

Im attempting to connect my console via USB to perform installs. I have successfully installed `tinfoil_driver.exe` and downloaded the latest `nut.exe` however when I plug in console in to my computer, the status of the USB connection remains "disconnected". Is there something I am missing?

My games still appear in the list and I am able to install things through Wifi so that part is working, but cannot figure out why USB wont connect.

**Comment by introkun** [comment]
Can you please check device manager? Are there any non-identified devices?

**Comment by AzukaChan** [comment]
@introkun I had a look and here's what appears whenever I plugin my console
![libnx](https://user-images.githubusercontent.com/42724187/97980823-1b8c5a80-1e1d-11eb-879e-8317da8a506a.PNG)

**Comment by introkun** [comment]
Please try to download this https://zadig.akeo.ie/
Then: Open Zadig. In Options enable **List All Devices**. Select **libnx USB comms**. Select the driver **libusbk** and click **Replace Driver**

**Comment by AzukaChan** [comment]
@introkun This worked perfectly! Thank you!

**Comment by chickenbroth3** [comment]
This helped me all these years later. TY!!!! <3
