### ISSUE TITLE
USB connection not working for MAC

### ISSUE THREAD

**Issue by gleutar** [blawar/nut#207]
I installed all necessary plugins and when I run "python3 nut.py", the window opens and I see that the USB is disconnected.
In the terminal I get this exception:
usb exception: No backend available

The switch is connected to the MAC but this still happens...
Anyone had trouble with this?

I'm using nut version 2.7

**Comment by introkun** [comment]
Could you please provide a full application log from the terminal here?

**Comment by gleutar** [comment]
> Could you please provide a full application log from the terminal here?

Here you go:

python3 nut.py
loaded user guest
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
                        ,;:;;,
                       ;;;;;
               .=',    ;:;;:,
              /_', "=. ';:;:;
              @=:__,  \,;:;:'
                _(\.=  ;:;;'
               `"_(  _/="`
                `"'
Loading NSPs from the configuration file
loaded file list in 0.00022699999999997722 seconds
Scanning NSPs on the filesystem
.
Tue Nov  3 14:50:02 2020 Server Starts - 0.0.0.0:9000
Saving NSPs to the configuration file
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available
usb exception: No backend available...
and so on...

**Comment by introkun** [comment]
Please try in the terminal:
`brew install libusb`
Please note, you should have homebrew installed.

**Comment by gleutar** [comment]
> Please try in the terminal:
> `brew install libusb`
> Please note, you should have homebrew installed.

Great! That did it!! Thanks a lot!
