### ISSUE TITLE
If you're getting git errors...

### ISSUE THREAD

**Issue by throwawayay** [blawar/nut#217]
History was recently rewritten to remove very old, now obsolete titledb references.
GIT repo shrunk from 6GB to 30MB.
Please re-check out the code to fix any `git` errors

```
git clone https://github.com/blawar/nut
Cloning into 'nut'...
remote: Enumerating objects: 1646, done.
remote: Counting objects: 100% (1646/1646), done.
remote: Compressing objects: 100% (871/871), done.
remote: Total 3952 (delta 793), reused 1617 (delta 774), pack-reused 2306
Receiving objects: 100% (3952/3952), 30.89 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (2387/2387), done.
```

**Comment by introkun** [comment]
Any actions to repo collaborators/users?

**Comment by throwawayay** [comment]
You can save (git stash) or export any WIP changes, then checkout to a fresh folder and re-apply.

Was cleaned with https://rtyley.github.io/bfg-repo-cleaner/ so it is unavoidable to force a re-checkout, as history was rewritten (but commit history was, as much as possible, preserved).

**Comment by introkun** [comment]
@all-contributors please add @throwawayay for bug, maintenance, doc, ideas
