### ISSUE TITLE
DZ - Are there any speed improvements that can be made for WAN users?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [blawar/nut#22]

**Comment by blawar** [comment]
There is, the issue is complicated because it is not all WAN.  Every http / ftp server I have tested has goten the same speed on my switch as when downloading from my PC, however some users report slower than PC WAN performance.  It is hard for me to troubleshoot something I cannot reproduce.

**Comment by ThatNerdyPikachu** [comment]
(actually, I'm talking about switch to PC that is slow)
