### ISSUE TITLE
Configure Dependabot for the repo

### ISSUE THREAD

**Issue by introkun** [blawar/nut#229]
@blawar please check this https://medium.com/better-programming/how-to-keep-your-dependencies-secure-and-up-to-date-92578c7f3c9c
This is an easy way to track updates of dependencies.

**Comment by introkun** [comment]
Please check the results in my fork https://github.com/introkun/nut/pulls

**Comment by throwawayay** [comment]
Why even bother with defining max version, and extra commits that are noise?
Just using `=~` or `==1.*` (or similar, use major version only) in the requirements.txt should be sufficient.
Ref: https://stackoverflow.com/questions/8795617/how-to-pip-install-a-package-with-min-and-max-version-range

**Comment by throwawayay** [comment]
Updated all but `pytest` & `pyfakefs` to PEP440 standards, can't test those two right now
