### ISSUE TITLE
Crashes with error code: 2168-0001 after exiting DZ

### ISSUE THREAD

**Issue by war3zlod3r** [blawar/nut#23]
Crashes with error code: 2168-0001 after exiting DZ since the commit 12 hours ago

**Comment by gjimenezf** [comment]
I have the same problem

**Comment by war3zlod3r** [comment]
this occurs 100% of the time, doesn't matter if anything was installed or not

**Comment by blawar** [comment]
update to the latest version, b button was accidently enabled in that build you are running.  Use home button to exit.

**Comment by war3zlod3r** [comment]
Thanks!
