### ISSUE TITLE
[Workarounded] PyQt5 Problem on MacOS Big Sur

### ISSUE THREAD

**Issue by introkun** [blawar/nut#232]
The latest PyQt5 release (5.15) doesn’t work on Big Sur (yet).
The workaround is simple: Downgrade your PyQt5 to 5.13.
`pip install PyQt5==5.13`

Taken from [here](https://keremkoseoglu.com/2020/11/14/pyqt5-problem-on-macos-big-sur-solved/).

**Comment by Mintume** [comment]
I was not able to run Nut on Big Sur. I tried your solution but got this message:

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement PyQt5==5.13 (from versions: none)
ERROR: No matching distribution found for PyQt5==5.13

>

**Comment by throwawayay** [comment]
Reread this - https://github.com/blawar/nut#installation-guide

**Comment by introkun** [comment]
> I was not able to run Nut on Big Sur. I tried your solution and installed PyQt 5.13 but after running command, got this message:
> 
> > Kiaaras-Air:nut-2.7 kiaara$ python3 nut.py
> > Traceback (most recent call last):
> > File "/Users/kiaara/Downloads/nut-2.7/nut.py", line 9, in 
> > import urllib3
> > ModuleNotFoundError: No module named 'urllib3'
> 
> >

@Mintume please use Python3

**Comment by V33m** [comment]
Unfortunately, this didn't work for me as I'm using pip3 and versions lower than 5.14 does not exist for pip3. What I did was to simply add `SYSTEM_VERSION_COMPAT=1` in front of `pip3` to install the latest version (PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel)

`SYSTEM_VERSION_COMPAT=1 pip3 install colorama pyopenssl requests tqdm unidecode Pillow BeautifulSoup4 urllib3 Flask pyusb pyqt5 google-api-python-client google-auth-oauthlib`

**Comment by throwawayay** [comment]
Try also latest version but with ENV set as:
`export QT_MAC_WANTS_LAYER=1`

**Comment by nikiizvorski** [comment]
Hey guys any solution for this? I haven't been able to get it done to my Mac i am on BugSur

**Comment by V33m** [comment]
There are three proposed solutions in the thread. Have you tried them all? If so, it would be easier to help you if you could provide us with more information such as error messages and so on 👍

**Comment by nffdiogosilva** [comment]
Is there a way to install this using python 2, with pip instead of pip3?

**Comment by throwawayay** [comment]
no, use pyenv to install python 3.9.7+
