### ISSUE TITLE
Deprecation warning in code

### ISSUE THREAD

**Issue by introkun** [blawar/nut#235]
`nut_gui.py:163: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.progress.setValue(i.i / i.size * 100)`

**Comment by throwawayay** [comment]
just `round` the value

**Comment by introkun** [comment]
@96RadhikaJadhav wanna try this one?

**Comment by 96RadhikaJadhav** [comment]
@introkun There is no 163 line number in nut_gui.py file. Could you please help in directing me to the correct file? I could see self.progress.setValue(i.i / i.size * 100) is in gui/progress.py file.

**Comment by introkun** [comment]
@96RadhikaJadhav yes, correct. I did a refactoring and split nut_gui.py into few smaller files.

**Comment by 96RadhikaJadhav** [comment]
A bit confusion here. Should it be round(self.progress.setValue(i.i / i.size * 100)) or self.progress.setValue(round(i.i / i.size * 100)) in progress.py file?

**Comment by blawar** [comment]
if you change the "/" to a "//", it will do integer division instead of float.

**Comment by blawar** [comment]
You would want to change the order to prevent rounding problems though:
self.progress.setValue(i.i * 100 // i.size)

**Comment by 96RadhikaJadhav** [comment]
> You would want to change the order to prevent rounding problems though:
> self.progress.setValue(i.i * 100 // i.size)

Okay, Thank You 👍

**Comment by 96RadhikaJadhav** [comment]
@introkun @blawar Created a PR. Please check and let me know if any other changes required.
