### ISSUE TITLE
[Bug] Nut incorrectly reports transfer speeds in the status bar.

### ISSUE THREAD

**Issue by Ryuhouji** [blawar/nut#245]
**Describe the bug**

**To Reproduce**

Transmit a file from Nut to Tinfoil.

**Expected behavior**
On Tinfoil, the rate is correctly displayed on the switch, in this case ~33MB/sec

**Screenshots**
https://i.imgur.com/ayZPr7T.png
https://i.imgur.com/JxKNVr1.jpg

**NUT version (or git hash):**
 v2.7 NUT on Windows 10 20H2

**Comment by eXhumer** [comment]
The problem is due to how NUT calculates times and use of time.time() to get seconds instead of time.perf_counter() (which is currently being used)
