### ISSUE TITLE
[Feature] expose existing filters in nut_gui

### ISSUE THREAD

**Issue by blawar** [blawar/nut#248]
The code code already supports a number of filters through command-line that are not exposed in the GUI.  Every property in the Config.Download class is a filter:  https://github.com/blawar/nut/blob/master/nut/Config.py#L699

The min/max settings are dependent on a double ended slide control which does not exist in Qt.  A custom one will likely need to be made, or work around it with less intuitive controls.

**Comment by introkun** [comment]
@all-contributors please add @blawar for code, bug, maintenance, doc, ideas, infra, question, review, tool
