### ISSUE TITLE
[Feature] Create double ended slider control

### ISSUE THREAD

**Issue by blawar** [blawar/nut#249]
Need a double ended slider control for the min/max settings in #248 

There might be some sort of vanilla control to do it in newer versions of Qt, unsure:

https://stackoverflow.com/questions/25155908/qt5-double-range-slider

**Comment by introkun** [comment]
Resolved d05ed5fb7bed0a1d76cfd82d35e5ff4eeb46c4ec

**Comment by introkun** [comment]
Relates to #281
