### ISSUE TITLE
[Bug] Some titledb json file downloads are incomplete

### ISSUE THREAD

**Issue by BryanWall** [blawar/nut#252]
Nut 3.0 (using the pre-compiled the Windows exe from Github) produces the following error when downloading titledb files:

> load titles (titledb/ZA.en.json) json exception: Expecting property name enclosed in double quotes: line 314912 column 5 (char 18346977)

I opened the file and found that the file which is auto-downloaded by nut is truncated after the "languages" element of item "70070000011123" at line 314912 of the file. I have deleted all traces of nut 3.0 and reinstalled it a couple of times, and also just deleted the titledb folder, but this issue persists. I confirmed that the version of the file on Github is complete and not truncated. 

I replaced my local files with all of the titledb files from github, deleted files.json, then rescanned, and it fixed several scanning and organizing/renaming issues with files whose data was in ZA.en.json.

**Comment by woolrage** [comment]
reproduced here

**Comment by introkun** [comment]
This is a known isssue. @blawar may I ask you to update the lang file?

**Comment by blawar** [comment]
should be fixed.  There is a missing CO.es.json file that should fix itself once the next cronjob runs tonight.

**Comment by blawar** [comment]
I confirmed everything is fix now that the cron job ran.  @introkun the issue was that ZA.en.json is the last file added to the archive, and the zstd handle was not flushed before it was closed, causing the last part of that file to be missing.  Flushing the handle before closing fixed the issue.
