### ISSUE TITLE
[Bug] nut_gui.exe crashes, failed to execute script nut_gui

### ISSUE THREAD

**Issue by pseudobacon** [blawar/nut#255]
When opening nut_gui.exe a crash occurs

![image](https://user-images.githubusercontent.com/12183854/103621813-e4a40380-4f89-11eb-9a70-79fdd6264f97.png)

**NUT version (or git hash):**
3.0

**Comment by introkun** [comment]
@pseudobacon I cannot reproduce. Could you please provide more details? Is it a new installation or you've updated from the previous version of NUT? Can you please attach some config files? Thanks.

**Comment by eXhumer** [comment]
I am not sure what causes this, but it also happened to me once. I will try to re-produce this if I can and report back.

**Comment by pseudobacon** [comment]
@introkun I downloaded it into a new directory. Its just a fresh copy of the exe, copied into a new directory. I've attached the configuration files here:
[conf.zip](https://github.com/blawar/nut/files/5785310/conf.zip)

Previous version (2.7) works fine without issue

**Comment by introkun** [comment]
@pseudobacon could you please attach titledb/files.json?

**Comment by pseudobacon** [comment]
As requested

[files.zip](https://github.com/blawar/nut/files/5792086/files.zip)

**Comment by peter765** [comment]
Was running into this issue

https://github.com/blawar/nut/blob/master/nut/Nsps.py#L156
The error on this line is missing a 'timestamp' field in the `titledb/files.json` directory. 

By adding a "timestamp" field and setting it to null, I was able to get NUT to open. 
`[
    {
        "extractedNcaMeta": 0,
        "fileSize": 4222706624,
        "hasValidTicket": true,
        "path": "../[NSP].nsp",
        // "timestamp": null, // added manually
        "titleId": "]-----]",
        "version": "0"
    },
`

**Comment by introkun** [comment]
@peter765 I've added some logging in the master branch to capture the issue with timestamp saving.
