### ISSUE TITLE
[Bug] nut exception: 'Namespace' object has no attribute 'cetk'

### ISSUE THREAD

**Issue by bao3** [blawar/nut#256]
**Describe the bug**
My OS: Debian 10
Python: 3.7
Nut Version: 3.0
My purpose: Run nut3.0 as a silent server to support network install.

But actually I got the error ` nut exception: 'Namespace' object has no attribute 'cetk' `.

**To Reproduce**
1. I install the modules in the requirement.txt bye `pip install -r requirement.txt` .
2. run "python3 ./nut.py -S" ,I got the errors as below:

> ~/nut-3.0# ./nut.py  --server --hostname homeserver           
>loaded user guest
>                                               ,;:;;,
>                                           ;;;;;
>                           .=', ;:;;:,
>                           /_', "=. ';:;:;
>                           @=:__,  \,;:;:\'
>                                 _(\.=  ;:;;\'
>                            `"_(  _/="`
>                                 `"'
> nut exception: 'Namespace' object has no attribute 'cetk'
> Traceback (most recent call last):
>   File "./nut.py", line 545, in <module>
>     if args.cetk:
> AttributeError: 'Namespace' object has no attribute 'cetk'
> 

And I commented the line 545 and so on , then I could start the server as normal.

**Comment by introkun** [comment]
Fixed in commit  80a1892 by @blawar
