### ISSUE TITLE
[Bug] Missing title size causes application to crash

### ISSUE THREAD

**Issue by eXhumer** [blawar/nut#260]
**Describe the bug**/**To Reproduce**
Happened when I browsed to a new folder and scanned it. This bug happens because for some reason, NUT fails to get the filesize of a file entry in `files.json`. As a result, NUT fails to abs() a NoneType. Removing the entry fixes the issue.

Faulty file entry in `files.json`
```
    {
        "extractedNcaMeta": 0,
        "fileSize": null,
        "hasValidTicket": true,
        "path": "C:\\Users\\eXhumer\\Downloads\\Switch Games\\Cadence of Hyrule \u2013 Crypt of the NecroDancer Featuring The Legend of Zelda\\Cadence of Hyrule Crypt of the NecroDancer Featuring The Legend of Zelda [Cadence of Hyrule Symphony of the Mask][01000B900D8B1003][US][v393216].nsz",
        "timestamp": 1610080596.8043642,
        "titleId": "01000B900D8B1003",
        "version": "393216"
    }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/62310242/103975492-7e59e500-5131-11eb-89e3-c61da44cd1a0.png)

**NUT version (or git hash):** v3.0 Windows Binary

If any more information required, don't hesitate to ask in comments.

**Comment by introkun** [comment]
@eXhumer please check my fix in the `master` branch and provide here a console output for any errors related to getting file size.

**Comment by introkun** [comment]
Added tests for this in 686789efcda

**Comment by introkun** [comment]
@all-contributors please add @eXhumer for bug, code
