### ISSUE TITLE
name 'cdn' is not defined 

### ISSUE THREAD

**Issue by xiaoyaoking** [blawar/nut#264]
name 'cdn' is not defined                                                                                                               
name 'cdn' is not defined                                                                                                               
name 'cdn' is not defined                                                                                                               
19104 titles scanned, downloading 0                                                                                                     
Downloads finished                                                                                                                      
DownloadAll finished                                                                                                                    
nut exception: name 'cdn' is not defined                                                                                                
Traceback (most recent call last):                                                                                                      
  File "/home/nut/nut.py", line 893, in <module>                                                                                        
    nut.scanLatestTitleUpdates()                                                                                                        
  File "/home/nut/nut/__init__.py", line 1417, in scanLatestTitleUpdates                                                                
    for k, i in cdn.hacVersionList().items():                                                                                           
NameError: name 'cdn' is not defined

**Comment by introkun** [comment]
@xiaoyaoking please try version from the `master` branch.

**Comment by introkun** [comment]
cdn features are not available in nut, please check the available functionality
