### ISSUE TITLE
An incorrect variable used in file Fs/driver/curl.py

### ISSUE THREAD

**Issue by introkun** [blawar/nut#266]
**Describe the bug**
An incorrect variable used in file Fs/driver/curl.py:15

**Screenshots**
![image](https://user-images.githubusercontent.com/61635/104124882-57372980-5364-11eb-9198-c38d73ef35e8.png)

**NUT version (or git hash):**
 - Git hash  b4a1e46 (v3.0)

**Comment by 96RadhikaJadhav** [comment]
@introkun Should sz be renamed to size here?

**Comment by introkun** [comment]
> @introkun Should sz be renamed to size here?

Looks like. Send your PR and we will see.

**Comment by 96RadhikaJadhav** [comment]
@introkun  For now I have just corrected sz to size in curl.py in line 15 and created a PR. Please et me know if other instances of sz also needs to be corrected in curl.py file.
