### ISSUE TITLE
[Bug] Ftp password is stored in a plain text in the nut.conf

### ISSUE THREAD

**Issue by introkun** [blawar/nut#279]
**Describe the bug**
Ftp password is stored in a plain text in the nut.conf

**To Reproduce**
Steps to reproduce the behaviour:
1. `python3 nut_gui.py`
2. Open `Remote Pull Paths` tab
3. Add new ftp server

**Actual behaviour**
Ftp password is stored in a plain-text format in the nut.conf

**Expected behaviour**
Ftp password (or even full path with user/host/port) is stored in an encrypted format in the nut.conf

**Screenshots**
![image](https://user-images.githubusercontent.com/61635/104639687-bf657280-56b8-11eb-9125-5e87b9eab078.png)

**NUT version (or git hash):**
 - Nut 3.0
 - Git hash 8efeac6

**Comment by throwawayay** [comment]
Not a bug, FTP itself is insecure and should only be used over trusted local network
