### ISSUE TITLE
[Bug] could not load keys.txt, all crypto operations will fail

### ISSUE THREAD

**Issue by andrewwuan** [blawar/nut#282]
**Describe the bug**
When I start nut_gui.exe, I got the error message `could not load keys.txt, all crypto operations will fail` from very start of the terminal. Other things would load as normal, but when I connect my switch, I'm not able to read anything from usb nor install games.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start nut_gui.exe.
2. Wait for GUI to load.
3. Connect switch.
4. Launch Tinfoil.

**Actual behaviour**
Can't install new games. USB menu is empty.

**Expected behaviour**
"New games" should show up, USB menu should show all nsps on my machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/3323729/104930968-c5bd5c80-59e0-11eb-8a2f-df0b64f655a3.png)

**NUT version (or git hash):**
 - Nut: 3.0

**Additional context**
Works before but stops working today. I removed conf & titledb folders and started nut_gui.exe again but problem persists.

**Comment by programatix** [comment]
You need to either dump the keys from your Switch or find it somewhere in the internet.

**Comment by introkun** [comment]
keys.txt is not relevant to the issue.
@andrewwuan could you please provide more logging info from the console? Is there anything happening after line "begin recv"?
What's your switch OS, what's Tinfoil version?

**Comment by jrdoublet** [comment]
I have the same pb , it's a proxy / connection error to github
![image](https://user-images.githubusercontent.com/13040399/108640658-4a494200-749b-11eb-9fbf-f65d6e580498.png)

I'll manage this with my firewall / proxy settings.

**Comment by rikelliott** [comment]
I have this problem as well connecting using USB. I have been using 2.7 without problems and it still works. 3.1 pauses for 5 secs then says cannot find keys.txt no other errors. The roms show up on the Windows PC but when selecting NSP from switch I just get a message saying it cannot open the NSP.

**Comment by runesbentor** [comment]
I have the same problem. I'm connecting my Switch via USB and can see the games but they appear as 0.0kB size and an error message pop up when I try to open them. "Failed to open NSP"


could not load keys.txt, all crypto operations will fail
                        ,;:;;,
                       ;;;;;
               .=\',    ;:;;:,
              /_\', "=. \';:;:;
              @=:__,  \,;:;:\'
                _(\.=  ;:;;\'
               `"_(  _/="`
                `"\'
loaded titledb/titles.json in 0.47037489999999993 seconds
loaded file list in 0.0043434999999996116 seconds
initThread start
scanning .
Mon May 10 12:36:38 2021 Server Starts - 0.0.0.0:9000
initThread finish
USB Connected
begin recv
read complete
invalid magic! b'/api'
failed to read!
begin recv

**Comment by throwawayay** [comment]
please retry with latest nut.py/nut.exe 3.2 & latest tinfoil.
reopen if still an issue

**Comment by HitcherUK** [comment]
Same issue for me as well with all versions after v2.7.

**Comment by JusorT** [comment]
all versions after 2.7 give me this error
![image](https://user-images.githubusercontent.com/88520902/128445580-d2c139b1-7f74-4628-9c33-acd623f64392.png)

**Comment by throwawayay** [comment]
fix you file names, they need to have titleid
(that one is [01002F00100A2000])

**Comment by SatoshiEK** [comment]
I have the exact same error. Tried using version 2.7 but also does not work. I manage to install one game normally, and right after that as I tried installing another one this started happening. Anybody found a solution for this already?
