### ISSUE TITLE
[Bug] Cannot start new version

### ISSUE THREAD

**Issue by SuperSpe** [blawar/nut#283]
**Describe the bug**
[8244] Failed to execute script nut_gui

**To Reproduce**
run nut_gui.exe

**Actual behaviour**
crash

**Expected behaviour**
the gui

**Screenshots**
could not load keys.txt, all crypto operations will fail
loaded user guest
                        ,;:;;,
                       ;;;;;
               .=\',    ;:;;:,
              /_\', "=. \';:;:;
              @=:__,  \,;:;:\'
                _(\.=  ;:;;\'
               `"_(  _/="`
                `"\'
loaded titledb/titles.json in 0.5046733000000001 seconds
Traceback (most recent call last):
  File "nut_gui.py", line 390, in <module>
  File "nut_gui.py", line 369, in run
  File "__init__.py", line 630, in initTitles
  File "__init__.py", line 640, in initFiles
  File "Nsps.py", line 142, in load
KeyError: 'timestamp'
[8244] Failed to execute script nut_gui

**NUT version (or git hash):**
 - Nut: 3.0 exe

**Additional context**
Windows 10 Pro. Older version works good

**Comment by blawar** [comment]
delete titledb/files.json

**Comment by introkun** [comment]
Fixed in master branch. Will create a windows package asap.

**Comment by introkun** [comment]
Fixed here https://github.com/blawar/nut/commit/60a53b7a4d46ce647cc8f6087ea668d445ac299e

**Comment by introkun** [comment]
Please downloaded latest release https://github.com/blawar/nut/releases/tag/v3.1
