### ISSUE TITLE
[Bug] Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by roadhazard** [blawar/nut#286]
**Describe the bug**

Trying to install Nut 3.1 on Debian 10 and first problem, libusb doesn't seem to exist:
sudo apt install libusb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libusb

Second problem:

sudo pip3 install colorama pyopenssl requests tqdm unidecode Pillow BeautifulSoup4 urllib3 Flask pyusb pyqt5 google-api-python-client google-auth-oauthlib
Collecting colorama
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting pyopenssl
  Downloading https://files.pythonhosted.org/packages/b2/5e/06351ede29fd4899782ad335c2e02f1f862a887c20a3541f17c3fa1a3525/pyOpenSSL-20.0.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 2.2MB/s 
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.21.0)
Collecting tqdm
  Downloading https://files.pythonhosted.org/packages/80/02/8f8880a4fd6625461833abcf679d4c12a44c76f9925f92bf212bb6cefaad/tqdm-4.56.0-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 5.8MB/s 
Collecting unidecode
  Downloading https://files.pythonhosted.org/packages/74/65/91eab655041e9e92f948cb7302e54962035762ce7b518272ed9d6b269e93/Unidecode-1.1.2-py2.py3-none-any.whl (239kB)
    100% |████████████████████████████████| 245kB 2.8MB/s 
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (5.4.1)
Collecting BeautifulSoup4
  Downloading https://files.pythonhosted.org/packages/d1/41/e6495bd7d3781cee623ce23ea6ac73282a373088fcd0ddc809a047b18eae/beautifulsoup4-4.9.3-py3-none-any.whl (115kB)
    100% |████████████████████████████████| 122kB 4.5MB/s 
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (1.24.1)
Collecting Flask
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 4.2MB/s 
Collecting pyusb
  Downloading https://files.pythonhosted.org/packages/b5/28/b857ac783257f142932b23379d761a3d9becf6deecf5d14075ec19bdb890/pyusb-1.1.1-py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 4.3MB/s 
Collecting pyqt5
  Downloading https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 543kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-sh3usmdi/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-sh3usmdi/pyqt5/

I'm a Linux newbie and was able to get Nut 2.7 installed and working but the latest version is giving me problems. Maybe I'm doing something wrong?

**To Reproduce**
Steps to reproduce the behaviour:
Follow directions to getting this running on Linux

**Actual behaviour**
Fails

**Expected behaviour**
python3 nut_gui.py should launch the GUI

**Screenshots**

**NUT version (or git hash):**
 - Nut: v2.7 is working

**Additional context**
Using Debian 10 stable.

**Comment by introkun** [comment]
@roadhazard regarding missing libusb: https://askubuntu.com/questions/820111/why-cant-i-install-libusb?answertab=active#tab-top

**Comment by introkun** [comment]
Please install Qt5 as a system package:
`sudo apt-get install python3-pyqt5`

**Comment by roadhazard** [comment]
@introkun Looks like I already have that stuff installed:

libusb-1.0-0 is already the newest version (2:1.0.22-2).
libusb-1.0-0 set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-headers-4.19.0-11-amd64 linux-headers-4.19.0-11-common
  linux-image-4.19.0-11-amd64
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

sudo apt install python3-pyqt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5 is already the newest version (5.11.3+dfsg-1+b3).
The following packages were automatically installed and are no longer required:
  linux-headers-4.19.0-11-amd64 linux-headers-4.19.0-11-common
  linux-image-4.19.0-11-amd64
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by introkun** [comment]
>python3-pyqt5 is already the newest version (5.11.3+dfsg-1+b3).
Our minimum supported version of Qt is 5.15.1...

**Comment by introkun** [comment]
@roadhazard could you please provide output in console:
> python3 nut_gui.py

**Comment by roadhazard** [comment]
@introkun Guess that explains things. :) And Debian being Debian..... guess I'll need to wait for 10.8 or 11 so I can get some newer packages. Thanks for helping me!

**Comment by roadhazard** [comment]
@introkun 

Traceback (most recent call last):
  File "nut_gui.py", line 11, in <module>
    import nut
  File "/home/roadhazard/Downloads/nut/nut/__init__.py", line 19, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by introkun** [comment]
>ModuleNotFoundError: No module named 'colorama'
run
>pip3 install colorama

**Comment by roadhazard** [comment]
@introkun 

could not load keys.txt, all crypto operations will fail
Traceback (most recent call last):
  File "nut_gui.py", line 11, in <module>
    import nut
  File "/home/roadhazard/Downloads/nut/nut/__init__.py", line 24, in <module>
    import Fs
  File "/home/roadhazard/Downloads/nut/Fs/__init__.py", line 3, in <module>
    from Fs.Nsp import Nsp
  File "/home/roadhazard/Downloads/nut/Fs/Nsp.py", line 22, in <module>
    from nut import blockchain
  File "/home/roadhazard/Downloads/nut/nut/blockchain.py", line 25, in <module>
    from flask import Flask, jsonify, request
ModuleNotFoundError: No module named 'flask'

**Comment by introkun** [comment]
>ModuleNotFoundError: No module named 'flask'

You need to install all the required libraries from requirements.txt, please try one by one

**Comment by introkun** [comment]
>pip3 install -к requirements.txt

**Comment by roadhazard** [comment]
@introkun 

When I do pip3 install -r requirements.txt, I get that big error in my OP. Using -k I get:

no such option: -к

I'll try them one by one..........

**Comment by roadhazard** [comment]
@introkun 

pip3 install pyqt5
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-zzfwg998/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zzfwg998/pyqt5/

.....bombed out on qt5. Will continue on with the others.........

**Comment by roadhazard** [comment]
@introkun ..... the rest installed fine except for these other two:

pip3 install pycurl
Collecting pycurl
  Downloading https://files.pythonhosted.org/packages/50/1a/35b1d8b8e4e23a234f1b17a8a40299fd550940b16866c9a1f2d47a04b969/pycurl-7.43.0.6.tar.gz (222kB)
    100% |████████████████████████████████| 225kB 3.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-y9ujncuz/pycurl/setup.py", line 237, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y9ujncuz/pycurl/setup.py", line 988, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-y9ujncuz/pycurl/setup.py", line 649, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-y9ujncuz/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-y9ujncuz/pycurl/setup.py", line 241, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-y9ujncuz/pycurl/
roadhazard@roadzard-pc:~/Downloads/nut$ pip3 install qt-range-slider
Collecting qt-range-slider
  Downloading https://files.pythonhosted.org/packages/2c/9d/e5dbf9088732661d9931762d196cf3feef73e4a7acfbe0637ad02399bb6d/qt_range_slider-0.2.3-py3-none-any.whl
Collecting pyqt5 (from qt-range-slider)
  Using cached https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-14groapf/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-14groapf/pyqt5/

**Comment by throwawayay** [comment]
seems like python dependeny issues.
use a clean virtualenv and retry - pip install -r requirements.txt
