### ISSUE TITLE
[Feature] Command line instead of GUI for use with a NAS.

### ISSUE THREAD

**Issue by Pesoen** [blawar/nut#290]
**Is your feature request related to a problem? Please describe.**
I would love a way to run the NUT server from a command line, without the GUI and the need for pyqt.

**Describe the solution you'd like**
Some way to run the nut server without an interface, purely using command line, or maybe a dedicated app to run on a synology nas, so i can access my games from it.

**Describe alternatives you've considered**
tried running the software from a command line, but it required pyqt, which could not install without a ton of other files that refuse to run on my NAS.

Keep in mind, it has been a while since i last tried, maybe it will work now, i cannot know for sure.

**Comment by blawar** [comment]
run nut.py for headless, not not_gui.py

**Comment by introkun** [comment]
And definitely you need to modify requirements.txt file to remove GUI stuff
