### ISSUE TITLE
[Bug] Tinfoil is not able to see files in usb/usbfs

### ISSUE THREAD

**Issue by oujiafan** [blawar/nut#291]
**Describe the bug**
Installed tinfoil_driver.exe. Used zadig to replace tinfoil interface driver to libusbk anyway.
Then connected to switch, but not able to see any file in "File Browse" - "usbfs".

**NUT version (or git hash):**
 - Windows 10
 - Nut: 2.7

**Comment by introkun** [comment]
@oujiafan please try v3.1

**Comment by emirefek** [comment]
Go Device Manager at windows. And check Tinfoil device is under unknown or another? If it is under unknown, click update driver, click see already installed drivers and select Tinfoil driver in there. That should be fix your issue, same thing happened in my pc.

**Comment by BrenoFortunato** [comment]
I have a similar error, I can see files in "usb", but their size are "0.0B".

When I try to access "usbfs" > "titles" (that's the folder where my files are) tinfoil freezes and the Nut console shows the message: 

> route exception: dir list access denied

If I press the home button, the Nut console shows: 

> usb exception: [Errno None] b'libusb0-dll:err [_usb_reap_async] reaping request failed, win error: a device connected to the system is not functioning

I'm on Windows 10, nut 3.1 and SX OS. Anyone manged to solve this problem?

**Comment by soralapio** [comment]
Same issue. My Switch is showing up correctly as Tinfoil under libusbK Usb Devices. I am using the latest Tinfoil drivers, Nut 3.1 and Tinfoil 12.0. If I manually browse to a folder containing installable files, they show up as 0.0 bytes. If I try to access something through usbfs, I get the following in the log:

url /api/directoryList/nameOfFileImTryingToAccess
routing to getDirectoryList
route exception: dir list access denied
begin recv

Tinfoil freezes, and if I force quit Tinfoil, I get:

usb exception: [Errno None] b'libusb0-dll:err [_usb_reap_async] reaping request failed, win error: A device attached to the system is not functioning.\r\n\n'

**Comment by throwawayay** [comment]
should be fixed in 3.2 (use latest tinfoil, nut/nut.exe and driver), please re-open if not

**Comment by frizzle101101** [comment]
not sure what i did but using the latest release 3.3 with tinfoil13 having issues with this too. just one thing to not i may have screwed my drivers or something because it did work once over usb but now not even with reinstall of drivers...any suggestions

**Comment by Danker1990** [comment]
> 
> 
> not sure what i did but using the latest release 3.3 with tinfoil13 having issues with this too. just one thing to note i may have screwed my drivers or something because it did work once over usb but now not even with reinstall of drivers...at some point i tried reinstalling using zadig on interface 1 and 0 ...lol i feel i screweed them but with the interface 1 as mtp device i can access the sd card from my computrers explorer...any suggestions to fix usbfs

Exactly the same situation. Also in my instances it seems to be 50/50 on wether it loads my data stored or comes up blank. i think the programme needs a bit more work and perhaps an update to nut.
