### ISSUE TITLE
[Feature] Add confirmation before moving files (organize)

### ISSUE THREAD

**Issue by windowswithoutborders** [blawar/nut#292]
Make the `organize files` button work only on confirm. Possibly even add an undo option too. Clicked into the nut server window and didn't realizing i was clicking organize files instead of the window border and I ended up "organizing" my files which I already had in a specific order. fortunately it is simple enough to script moving the files back to the original locations thanks to the nut console output, but that's a pretty destructive option to have work without any confirmation.

**Comment by throwawayay** [comment]
Undo is not possible however you can use `--dry` in the CLI to preview

**Comment by flacito13** [comment]
This fucking "organize files" just deleted 90% of my fucking nsp files!!! What the fuck!
