### ISSUE TITLE
[Bug] ImportError: pycurl

### ISSUE THREAD

**Issue by kevinwt95** [blawar/nut#298]
Hey, I followed the guide on Mac. If trying to run "python3 nut_gui.py " it says:
`could not load keys.txt, all crypto operations will fail
loaded user guest
Traceback (most recent call last):
...
 import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)`

**Comment by merhong2012** [comment]
I have the same problem。

**Comment by throwawayay** [comment]
Can you try with a clean pyenv? post pip installed list as well

**Comment by introkun** [comment]
Try this:
`pip uninstall pycurl
export PYCURL_SSL_LIBRARY=openssl
pip install pycurl`

**Comment by throwawayay** [comment]
yeah this command should have the same effect, although if pycurl was already installed it would need to be uninstalled first
```
PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install --no-cache-dir pycurl
```

**Comment by idkwhojamesis** [comment]
> yeah this command should have the same effect, although if pycurl was already installed it would need to be uninstalled first
> 
> ```
> PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install --no-cache-dir pycurl
> ```

Out of the solutions posted here and on #395 for the pycurl import error, this is the only one that has worked for me (macOS 11.3)

**Comment by timbroder** [comment]
If anyone else finds this, this worked for me:

```
OPENSSL_DIR=$(brew --prefix openssl) \
LDFLAGS="-L${OPENSSL_DIR}/lib" CPPFLAGS="-I${OPENSSL_DIR}/include" \
PKG_CONFIG_PATH="${OPENSSL_DIR}/lib/pkgconfig" \
pip install pycurl
```
