### ISSUE TITLE
[Bug] "Unsupported Architecture" error on macOS

### ISSUE THREAD

**Issue by ghost** [blawar/nut#301]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the installations instructions for macOS

**Actual behaviour**
Many  "#error architecture not supported" errors

**Expected behaviour**
Nut installs sucessfully

**Screenshots**

**NUT version (or git hash):**
 - Nut: 3.1 latest
 - Git hash [e.g. 0ab237f]

**Additional context**
Python version is 3.9.4 according to pyenv version
macOS version is 10.15.7

**Comment by introkun** [comment]
please provide more logs/console output

**Comment by introkun** [comment]
`which python3`

**Comment by tsuihak** [comment]
Traceback (most recent call last):
  File "/Users/genilsonsilva/nut/nut_gui.py", line 12, in <module>
    import Server
  File "/Users/genilsonsilva/nut/Server/__init__.py", line 21, in <module>
    import Server.Controller.Api
  File "/Users/genilsonsilva/nut/Server/Controller/Api.py", line 26, in <module>
    import Fs.driver.init
  File "/Users/genilsonsilva/nut/Fs/driver/init.py", line 2, in <module>
    import Fs.driver.curl
  File "/Users/genilsonsilva/nut/Fs/driver/curl.py", line 1, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)

**Comment by throwawayay** [comment]
@tsuihak re-read the readme, this is a libcurk issue

**Comment by tsuihak** [comment]
I followed the 2 procedures below in MacOS Big Sur 11.5.2 and both did not work showing the same error.

-------------------------------------------------------------------------------------------------------------------------
NUT (Switch)

1. Install Python 3.6+ from your preferred package manager, along with the libusb, python3-pip & python3-pyqt5 packages.
sudo mkdir /usr/local/Frameworks
sudo chown $(whoami) /usr/local/Frameworks
brew install python
brew install libusb
2. Install curl with the openssl backend. For Mac, follow this, and set install options: export PYCURL_SSL_LIBRARY=openssl
brew upgrade
brew uninstall curl
brew install curl-openssl
echo 'export PATH="/usr/local/opt/curl-openssl/bin:$PATH"' >> ~/.zshrc
3. Clone this repository to desired directory and change your working directory to the cloned repository.
git clone https://github.com/blawar/nut.git
4. Install the PIP modules with the following command pip3 install -r requirements.txt. If you previously tried installing pycurl and get the error libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other), uninstall it, make sure to follow step 2 again (installing curl with the openssl backend), and pip install pycurl --no-cache-dir
5. (Linux only) Add the following code snippet to /etc/udev/rules.d/99-switch.rules using your favorite editor.
SUBSYSTEM=="usb", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="27e2", GROUP="plugdev"
6. Run python3 nut_gui.py to launch the application.

-----------------------------------------------------------------------------------------------------------------------
NUT v2 (Switch)


1. Install Homebrew https://brew.sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
2. Install Python 3.6+ from your preferred package manager, for example: pyenv + pyenv-virtualenv (brew install pyenv pyenv-virtualenv and follow install directions)
3. Install libusb (brew install libusb)
4. Install curl with the openssl backend (brew install curl-openssl)
5. Clone this repository to desired directory and change your working directory to the cloned repository (git clone https://github.com/blawar/nut.git)
6. (Optional, but highly recommended) Create a virtualenv and activate it (pyenv virtualenv nut && source activate nut) - Não funcionou
7. Install pycurl using one of the below. Read this for more details
PYCURL_SSL_LIBRARY=openssl LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" pip install --no-cache-dir pycurl
or try
pip install --install-option="--with-openssl" --install-option="--openssl-dir=/usr/local/opt/openssl" pycurl
8. Install all other dependencies (pip install -r requirements.txt)
9. Run python nut_gui.py to launch the application

**Comment by introkun** [comment]
> ImportError: pycurl: libcurl link-time ssl backends (secure-transport, openssl) do not include compile-time ssl backend (none/other)


I'm having same issue in the CI while running GUI tests:
https://github.com/blawar/nut/runs/3579441481?check_suite_focus=true#step:9:55

**Comment by introkun** [comment]
could be a solution https://gist.github.com/webinista/b4b6a4cf8f158431b2c5134630c2cbfe

**Comment by introkun** [comment]
Should be resolved in master after 23df0478a1a7abeb324bef444cb15dfd2020932c
