### ISSUE TITLE
[Bug] High RAM usage > 1.5Gb

### ISSUE THREAD

**Issue by lbesnard** [blawar/nut#302]
**Describe the bug**
Thanks for a great tool. I'm using nut-server in a docker environment with https://github.com/ramdock/nut-server, which pulls the latest version of NUT from tinfoi.io (see DockerFile https://github.com/ramdock/nut-server/blob/master/Dockerfile)

The container is constantly running on my machine, but I noticed that ```nut.py``` is using quite a lot of RAM > 1.5Gb which seems quite excessive, even when I'm not using NUT to install any game. 

**NUT version (or git hash):**
 - Nut: 3.1
 - Git hash: 3ead3d9c843b28975d9769d915d5f4b1a07a09d4

**Comment by introkun** [comment]
Cannot reproduce on MacOS @lbesnard 
![image](https://user-images.githubusercontent.com/61635/118181472-79d76d00-b440-11eb-8b53-62005a726b1e.png)

**Comment by lbesnard** [comment]
hum that's significantly less! I'll try to see if I can dig in further
