### ISSUE TITLE
[Bug] Could not load keys.txt

### ISSUE THREAD

**Issue by luisneto96** [blawar/nut#303]
When I run Nut it texts  "could not load keys.txt, all crypto operations will fail" in the first sentence. I am using the latest Tinfoil drivers, Nut 3.1 and Tinfoil 12.0. I also cannot find any directories on Tinfoil

**To Reproduce**
1- Run Nut

**Actual behaviour**
"could not load keys.txt, all crypto operations will fail"
After this every scan gets an error: could not get title id from filename, name needs to contain [titleId] : C:\Users\CLIENTE\Desktop\Switch\Jogos Switch\Super Smash Bros. Ultimate\Update\Super Smash Bros. Ultimate v6.1.0 [UPD].nsp

**Expected behaviour**
Just scan everything lol 

**Screenshots**
![nutbug](https://user-images.githubusercontent.com/85031157/120077998-9c45c900-c083-11eb-9a84-93c5fab5d130.png)

**NUT version (or git hash):**
 - Nut 3.1

**Additional context**

**Comment by Masamune3210** [comment]
You failed to mention where your keys.txt is stored and if its filled out correctly. Also the error about not getting the titleid is due to the nsp file being named incorrectly, it has to contain the titleid inside of square brackets somewhere in the filename for nut to pick  it up correctly

**Comment by luisneto96** [comment]
> 
> 
> You failed to mention where your keys.txt is stored and if its filled out correctly. Also the error about not getting the titleid is due to the nsp file being named incorrectly, it has to contain the titleid inside of square brackets somewhere in the filename for nut to pick it up correctly

I managed to get an keys.txt file from another homebrew and solved this. But why my already installed games by Nut didn't had this titleid problem? I didn't renamed them or anything

**Comment by blawar** [comment]
You can ignore the keys.txt error if you are just serving the games to install for tinfoil.  The keys are needed for more advanced options.
