### ISSUE TITLE
[Bug] dlc not installing from xci

### ISSUE THREAD

**Issue by astigb** [blawar/nut#306]
**Describe the bug**
Failed to install dlc packaged in cxci from nut.
Cxci can install fine from USB.

**To Reproduce**
Store cxci on nut (game+update+dlc)
Open tinfoil
Click xci in left menu
Install cxci

**Actual behaviour**
Game and update installs, then closes install window. No dlc installed.

**Expected behaviour**
Entire cxci should install. Game + update + dlc.

**NUT version (or git hash):**
 - Nut: 3.1
 - Tinfoil 12 r4

**Additional context**
This used to work.
Install updates,dlc from xci = yes

**Comment by blawar** [comment]
Is the DLC unsigned?  Tinfoil wont install unsigned DLC.  A lot of people modify the DLC for CXCI.  However this behavior might be changed.

**Comment by astigb** [comment]
Thanks for the reply and the great work. Sorry I am not sure about signatures. I assume they are signed. I use default settings on NSC Builder to make them. However if I convert the cxci to a ticketless cnsp everything installs from nut.

**Comment by blawar** [comment]
Fixed in latest tinfoil.
