### ISSUE TITLE
NUTFS protocol - Local scan path directory listing empty on switch

### ISSUE THREAD

**Issue by hoonyeah** [blawar/nut#307]
**Describe the bug:**

Nut 3.1
Tinfoil 12.0
NUTFS via LAN

Issue - Directory listings for specified "local scan paths" are empty on switch.

I do, however, see root drive listings and am able to browse through windows trees to find files and the directory contents does successfully load this way. (I am opening another bug to hopefully lock this down and **not** show all drives connected to NUT server, but this is unrelated.)

**Reproduce**

    Start nut gui 3.1
    Wait for GUI to load.
    Connect switch.
    Launch Tinfoil 12.0
    Configure Local Scan Path on NUT GUI
    Configure NUTFS path to local LAN pc on switch
    Browse to configured NUTFS path on switch

**Actual behavior**
Initial Directory listing:
SWITCH    --< configured local path
B    --< Local root drive on nut server
C    --< Local root drive on nut server
X    --< Local root drive on nut server

Drill into SWITCH, and it's empty.
Confirmed was working on Nut 2.5

**Expected behavior**
Drill into configured local path and directory contents should load.

**Comment by blawar** [comment]
This should be fixed in master, can you confirm?

**Comment by hoonyeah** [comment]
Dumb comment from dumb windows user. Do I have to compile?
Did not work with latest windows executable, but that's dated January.
https://github.com/blawar/nut/releases/tag/v3.1

**Comment by blawar** [comment]
you will have to wait until we do another binary release if you cant run from source @hoonyeah .  Will likely be next week.

**Comment by throwawayay** [comment]
should be fixed in 3.2 (use latest tinfoil, nut/nut.exe and driver), please re-open if not
