### ISSUE TITLE
[Bug] NUTFS insecure directory listing

### ISSUE THREAD

**Issue by hoonyeah** [blawar/nut#308]
**Describe the bug:**

Nut 3.1
Tinfoil 12.0
NUTFS via LAN

Issue - Directory listings shows all local drives on NUT server (not just specified local paths, etc).

Details: Looking to share with local lan users my "configured local path," not ALL my server drives and contents.

**Reproduce**

    Start nut gui 3.1
    Wait for GUI to load.
    Connect switch.
    Launch Tinfoil 12.0
    Configure Local Scan Path on NUT GUI
    Configure NUTFS path to local LAN pc on switch
    Browse to configured NUTFS path on switch

**Actual behavior**
Initial Directory listing:
SWITCH    --< configured local path
B    --< Local root drive on nut server
C    --< Local root drive on nut server
X    --< Local root drive on nut server

**Expected behavior**
Initial Directory listing:
SWITCH    --< configured local path
[nothing else]

**Comment by blawar** [comment]
Will add an option to disable that.

**Comment by hoonyeah** [comment]
> Will add an option to disable that.

Thank you!!!

**Comment by blawar** [comment]
There is an option for this in master, next binary release will have it: https://github.com/blawar/nut/commit/7380fdec116fb5e7949d2e5824f9211ecf470211

**Comment by hoonyeah** [comment]
> 
> 
> There is an option for this in master, next binary release will have it: [7380fde](https://github.com/blawar/nut/commit/7380fdec116fb5e7949d2e5824f9211ecf470211)

Hello again.

Not seeing the option yet in latest binary and issue persists. Maybe I missed it though.

Nut 3.3
Tinfoil 12.10

Directory listing shows ALL drives of host Windows machine.

Thanks!
