### ISSUE TITLE
[Bug] Nut or USB drivers no longer work in windows 11

### ISSUE THREAD

**Issue by aaronindhouse** [blawar/nut#310]
**Describe the bug**
In windows 11 the switch is able to interact with tegra rcm gui and things like that, but it is not detected as connected in nut after installing the nut drivers. I have confirmed that things work fine on a windows 10 pc. I figure it has got to be either an issue with the drivers with windows 11 or some small thing within nut itself that has to be changed for windows 11.

**To Reproduce**
Steps to reproduce the behaviour:

**Actual behaviour**

**Expected behaviour**

**Screenshots**

**NUT version (or git hash):**
 - Nut: 3.3
 - Git hash [e.g. 0ab237f]

**Additional context**

**Comment by throwawayay** [comment]
pre-release OSes are not technically supported

Post device manager screenshots and Tinfoil console. Try with and without MTP

**Comment by aaronindhouse** [comment]
After trying to open the the switch through MTP, nut will now detect the
switch as connected. However, MTP transfer does not seem to be working
quite right.
[image: xSRvtYdQ0g.jpg]

**Comment by throwawayay** [comment]
https://github.com/blawar/nut/issues/314 for MTP
