### ISSUE TITLE
[Bug] Killed while launching nut.py in the docker

### ISSUE THREAD

**Issue by bao3** [blawar/nut#312]
**Describe the bug**
I'm building a docker image for Synology NAS . In the last year I used nut 2.7 ~ 3.0 well , and today I built an image for nut3.0 , however when I tried to start the server , I got " Killed" message ,and nut.py stopped.

**To Reproduce**
Steps to reproduce the behaviour:
1.  use this Dockerfile I wrote to build an image:<br/>
```
FROM python:latest
#Download the latest Nut archive
RUN wget https://github.com/blawar/nut/archive/refs/tags/v$(curl --silent  https://api.github.com/repos/blawar/nut/releases/latest  | grep -Po '"tag_name": "v\K.*?(?=")').tar.gz -O nut.tar.gz
RUN mkdir /nut && tar zxf nut.tar.gz -C /nut --strip-components 1
WORKDIR /nut
RUN pip install -r requirements.txt
#use the default configure file but change to scan /mnt folder which would be linked to game title folder in Synology NAS 
RUN sed -i 's/\"scan\":\ \[\"\.\"\]/\"scan\":\ \[\"\/mnt\"\]/' conf/nut.default.conf 
RUN cp conf/nut.default.conf conf/nut.conf

#change keys.txt folder to /mnt . Then you just need to put your keys.txt into your Synology NAS
RUN sed -i 's/keys\.txt/\/mnt\/keys\.txt/g' `grep keys\.txt -rl ./`
VOLUME /mnt
CMD ["python", "nut.py","-S"]

```
2.  Run the container `docker run -it --rm -v /srv/titles:/mnt/ bao3/ns_nut  bash `. This command would mount my /srv/titles folder as "/mnt" 
3.  Run ` python nut.py -S`
4. Got "Killed" message

**NUT version (or git hash):**
 - Nut: 3.3

**Additional context**
Log as the bellow:
> 
> root@c56d220c58bc:/nut# python nut.py -S
> loading blacklist /nut/conf/blacklist.online.txt
> loaded user guest
>                         ,;:;;,
>                        ;;;;;
>                .=',    ;:;;:,
>               /_', "=. ';:;:;
>               @=:__,  \,;:;:'
>                 _(\.=  ;:;;'
>                `"_(  _/="`
>                 `"'
> downloading titledb files
> could not get title id from filename, name needs to contain [titleId] : titledb/db.nza                                                            
> unknown extension titledb/db.nza
> loaded titledb/CO.en.json in 0.024147543008439243 seconds
> loaded titledb/CO.es.json in 0.02404923504218459 seconds
> loaded titledb/AR.en.json in 0.01624199701473117 seconds
> loaded titledb/AR.es.json in 0.023464670055545866 seconds
> loaded titledb/CL.en.json in 0.014618735993281007 seconds
> loaded titledb/CL.es.json in 0.01627645397093147 seconds
> loaded titledb/PE.en.json in 0.0339529940392822 seconds
> loaded titledb/PE.es.json in 0.024661699077114463 seconds
> loaded titledb/KR.ko.json in 0.11937668395694345 seconds
> loaded titledb/HK.zh.json in 0.100440070964396 seconds
> loaded titledb/CN.zh.json in 0.000565266003832221 seconds
> loaded titledb/NZ.en.json in 0.2336548949824646 seconds
> loaded titledb/AT.de.json in 0.3223152889404446 seconds
> loaded titledb/BE.fr.json in 0.40199344302527606 seconds
> loaded titledb/BE.nl.json in 0.460754745057784 seconds
> loaded titledb/CZ.en.json in 0.516736806021072 seconds
> loaded titledb/DK.en.json in 0.4325386140262708 seconds
> loaded titledb/ES.es.json in 0.5498875409830362 seconds
> loaded titledb/FI.en.json in 1.7679932549363002 seconds
> loaded titledb/GR.en.json in 0.12658029107842594 seconds
> loaded titledb/HU.en.json in 0.42581769998651 seconds
> loaded titledb/NL.nl.json in 12.544495675945655 seconds
> loaded titledb/NO.en.json in 0.2330510210013017 seconds
> loaded titledb/PL.en.json in 0.4209459179546684 seconds
> loaded titledb/PT.pt.json in 0.11663526599295437 seconds
> Killed

**Comment by throwawayay** [comment]
related: https://github.com/blawar/nut/issues/309

**Comment by bao3** [comment]
Close that , it worked ,after I increate the memory to 2048MB .
