### ISSUE TITLE
[Bug] Cannot transfer files via USB

### ISSUE THREAD

**Issue by grskift** [blawar/nut#313]
**Describe the bug**
Sending files via USB does not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Tinfoil and Nut
2. Attempt to install a game/update

**Actual behaviour**
Tinfoil crashes - "The software was closed because an error occurred".
Nut reports this error:
```
begin recv
usb exception: [Errno None] b'libusb0-dll:err [_usb_reap_async] reaping request failed, win error: A device attached to the system is not functioning.\r\n\n'
````

**Expected behaviour**
The file transfer completes successfully.

**NUT version (or git hash):**
 - Nut: 3.3 on Windows 10
 - Git hash 7f3a0a3

**Additional context**
Using Tinfoil 12.10.
This does not happen with all files but seems very consistent. The error appears quickly. For large files, the GUI continues to show the transfer speed/amount although nothing is being sent.

**Comment by grskift** [comment]
I probably need to migrate to Atmosphere. This might be a non-issue. Can anyone confirm?

**Comment by throwawayay** [comment]
Might be https://github.com/blawar/nut/issues/314
Might be due to CFW
