### ISSUE TITLE
[Feature] Raspberry Pi Support/Docker

### ISSUE THREAD

**Issue by Pesoen** [blawar/nut#330]
**Is your feature request related to a problem? Please describe.**
a docker image that works on a raspberry pi. since no matter how i try, it refuses to work with all docker images i find, and installing python 3.9.7 and installing it all creates errors as well.. it just refuses to run(decided to host it on a pi instead of my nas, since it has more power)

**Describe the solution you'd like**
a way to just run this on a raspberry pi, without too much installation..

**Describe alternatives you've considered**
i have looked at the docker images on docker hub, but none work on an armv7 system, only other alternative is to repurpose an old laptop to host it all, or continue using my main computer to host it all, but would much rather have it somewhere else, that is always running.

**Comment by throwawayay** [comment]
This should work, if it doesn't, paste exact logs

https://github.com/blawar/nut#usage-guide-unix-users

**Comment by throwawayay** [comment]
Docker is an open issue, although there are some third party images:
https://github.com/blawar/nut/issues/309

**Comment by Pesoen** [comment]
> Docker is an open issue, although there are some third party images:
> #309

tried that image, does not work on armv7 devices(such as the raspberry pi)

**Comment by Pesoen** [comment]
> This should work, if it doesn't, paste exact logs
> 
> https://github.com/blawar/nut#usage-guide-unix-users

will redo it during the week, will post results.

**Comment by shawly** [comment]
My image should work with most architectures https://github.com/shawly/docker-nut
```docker pull shawly/nut```

**Comment by Pesoen** [comment]
> My image should work with most architectures https://github.com/shawly/docker-nut `docker pull shawly/nut`

it seems to be working, really nice :) gotta get my switch back(lent it out to a friend) before i can confirm, but the docker container is working, so i suspect it's working as expected.

**Comment by throwawayay** [comment]
> My image should work with most architectures https://github.com/shawly/docker-nut `docker pull shawly/nut`

Nice job, if you need any features/config exposed or clarified let me know.

the port for the server is set to 9000 by default but is modifiable

**Comment by shawly** [comment]
Thanks, it works pretty much flawless like it is already. The image is way smaller than most other images out there as its based on alpine and as far as I can see it is the only image that supports ARM SoCs. I also maintain it regularly, the automatic build allows me to easily push new versions if there is an update for NUT.

Though I did find a bug, if you duplicate the nut.default.conf as nut.conf, NUT fails to start with: 
```
AttributeError: module 'collections' has no attribute 'Mapping'
Failed to load config file: conf/nut.conf
Traceback (most recent call last):
  File "/nut/nut.py", line 18, in <module>
    from nut import Title
  File "/nut/nut/__init__.py", line 24, in <module>
    import Fs
  File "/nut/Fs/__init__.py", line 1, in <module>
    from Fs.Xci import Xci
  File "/nut/Fs/Xci.py", line 2, in <module>
    from Fs.File import File
  File "/nut/Fs/File.py", line 4, in <module>
    from nut import Print
  File "/nut/nut/Print.py", line 1, in <module>
    from nut import Status
  File "/nut/nut/Status.py", line 4, in <module>
    from nut import Config
  File "/nut/nut/Config.py", line 871, in <module>
    load('conf/nut.conf')
  File "/nut/nut/Config.py", line 323, in load
    original = dict_merge(original, j)
  File "/nut/nut/Config.py", line 48, in dict_merge
    and isinstance(merge_dct[k], collections.Mapping)):
```

Not sure if this is reproducable with the standalone version of NUT but it is reproducable with my image.

Also if you import the titledb from the Git repo it throws an exception at the end, it probably can be ignored but it's strange seeing an exception with the message `0` on a successful import:
```
...
loaded titledb/versions.txt in 3.14283206500113 seconds
nut exception: 0
Done.
```

**Comment by Pesoen** [comment]
shawly's docker image worked for me, closing the issue, but maybe look into linking him somewhere, as it just works after the setup part of it is done :D

**Comment by Guling85** [comment]
> Thanks, it works pretty much flawless like it is already. The image is way smaller than most other images out there as its based on alpine and as far as I can see it is the only image that supports ARM SoCs. I also maintain it regularly, the automatic build allows me to easily push new versions if there is an update for NUT.
> 
> Though I did find a bug, if you duplicate the nut.default.conf as nut.conf, NUT fails to start with:
> 
> ```
> AttributeError: module 'collections' has no attribute 'Mapping'
> Failed to load config file: conf/nut.conf
> Traceback (most recent call last):
>   File "/nut/nut.py", line 18, in <module>
>     from nut import Title
>   File "/nut/nut/__init__.py", line 24, in <module>
>     import Fs
>   File "/nut/Fs/__init__.py", line 1, in <module>
>     from Fs.Xci import Xci
>   File "/nut/Fs/Xci.py", line 2, in <module>
>     from Fs.File import File
>   File "/nut/Fs/File.py", line 4, in <module>
>     from nut import Print
>   File "/nut/nut/Print.py", line 1, in <module>
>     from nut import Status
>   File "/nut/nut/Status.py", line 4, in <module>
>     from nut import Config
>   File "/nut/nut/Config.py", line 871, in <module>
>     load('conf/nut.conf')
>   File "/nut/nut/Config.py", line 323, in load
>     original = dict_merge(original, j)
>   File "/nut/nut/Config.py", line 48, in dict_merge
>     and isinstance(merge_dct[k], collections.Mapping)):
> ```
> 
> Not sure if this is reproducable with the standalone version of NUT but it is reproducable with my image.
> 
> Also if you import the titledb from the Git repo it throws an exception at the end, it probably can be ignored but it's strange seeing an exception with the message `0` on a successful import:
> 
> ```
> ...
> loaded titledb/versions.txt in 3.14283206500113 seconds
> nut exception: 0
> Done.
> `
vi I got this error how do I fix this?
