### ISSUE TITLE
[Bug] Error message during updating of titleDB in non EN language

### ISSUE THREAD

**Issue by introkun** [blawar/nut#343]
**Describe the bug**
Error message during updating of titleDB in non EN language (e.g. RU)
`Could not locate US/ru !`

**To Reproduce**
Steps to reproduce the behaviour:
1. set language to RU in config file
2. restart nut gui
3. press 'Update TitleDB' top button

**Actual behaviour**
Error `Could not locate US/ru !` in console

**Expected behaviour**
No error messages in console

**NUT version (or git hash):**
 - Nut: 3.3
 - Git hash 750da3b0b123af5a7fd43f76445839568db665cc

**Comment by throwawayay** [comment]
Does this happen in command line as well?

**Comment by introkun** [comment]
> Does this happen in command line as well?

Yes. 
![image](https://user-images.githubusercontent.com/61635/134804410-0436f4ed-fa90-47b2-81cd-5f1a575e7906.png)

**Comment by introkun** [comment]
Ahh. This is my mistake. I've used "ru" language for "US" region. I've fixed it by adding region "RU" to the config file.

**Comment by throwawayay** [comment]
possible options are https://github.com/blawar/titledb/blob/master/languages.json
