### ISSUE TITLE
[Bug] Error while downloading TitleDB 

### ISSUE THREAD

**Issue by introkun** [blawar/nut#348]
**Describe the bug**
Error message in console while downloading TitleDB:
`downloading titledb files
could not get title id from filename, name needs to contain [titleId] : titledb/db.nza
unknown extension titledb/db.nza
loaded titledb/CO.en.json in 0.11161329200000125 seconds
loaded titledb/CO.es.json in 0.015417165999998872 seconds`

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove `titledb/titles.json` file
2. Start nut: `python3 nut.py -S`

**Actual behaviour**
Error message in console "could not get title id from filename, name needs to contain [titleId] : titledb/db.nza"

**Expected behaviour**
No error message

**NUT version (or git hash):**
 - Nut: 3.3
 - Git hash bbd1eec6238abd37c01c4186a6f3af98025e7b11

**Comment by throwawayay** [comment]
Artifact of downloading compressed db from tinfoil.media, unlikely to get fixed. If you don't prefer this, check out titledb as a git repo.

```
rm titledb
git clone https://github.com/blawar/titledb titledb
git -C titledb pull
nut.py -U --import-region US --language en
```

**Comment by introkun** [comment]
@blawar your word here? @throwawayay let's keep this issue open until we receive @blawar 's answer

**Comment by shawly** [comment]
The error message appears nonetheless even while importing the titledb from Git:
```
2021-11-08T09:52:12.052307536Z downloading titledb files
2021-11-08T09:52:12.052320070Z could not get title id from filename, name needs to contain [titleId] : titledb/db.nza
2021-11-08T09:52:12.052332939Z unknown extension titledb/db.nza
2021-11-08T09:52:12.052345247Z loaded titledb/BG.en.json in 0.2624959489912726 seconds
```

Not sure if this message can be disregarded anyway, the `db.bin` file is generated and NUT seems to be working fine without any issues.

**Comment by introkun** [comment]
@blawar any way to fix this?

**Comment by throwawayay** [comment]
No, other than changing the scan location entirely. You can delete db.nza after update, or ignore it entirely if using git

**Comment by AlmighalX** [comment]
Same here 😣
