### ISSUE TITLE
[Bug] Usbfs empty on tinfoil 13.0

### ISSUE THREAD

**Issue by scorpionz89** [blawar/nut#363]
**Describe the bug**
usbfs:/ empty , when launching tinfoil and nut usbfs is empty no drives. It shows connected on Nut but usbfs still empty. Tried to turn off MTP same issue. Downgraded tinfoil 11 usbfs worked but gave me access denied error when trying to access certain directories in my PC like desktop folder.

**To Reproduce**
Steps to reproduce the behaviour:

I Have Switch firmware 13.0, Clean install installed Atmosphere 1.1.1, installed Tinfoil 13.0, latest sigpatches, Nut 3.3 with tinfoil driver only not zadig. Launching Atmosphere through and sd card eMMC using Fusee bin.

**Actual behaviour**

**Expected behaviour**
Nut shows connected but surprised that usbfs shows empty and no directories

**NUT version (or git hash):**
 - Nut: 3.3
 

Thank you

**Comment by throwawayay** [comment]
What OS?
Using 3.3 release or master (via python)?
Post the `server` part of your nut.conf

**Comment by scorpionz89** [comment]
> Same issue here. Sadly the tinfoil driver does not show in my device manager for the fix

Not sure if you did same as me, but I had disabled MTP, then plugged in the switch, and had both Nut open the PC, and Tinfoil open on the switch and plugged in the PC usb before going to device manager, if you installed Tinfoil driver the first it should be under libusbk,

**Comment by HUMBLExSWAGGER** [comment]
same issue, opening hbm by holding r + opening an installed game fixed it for me. opening in applet mode was the issue i believe.

**Comment by HUMBLExSWAGGER** [comment]
also, usb-c to usb-c does not work for me, usb-a to usb-c does.

**Comment by drizuid** [comment]
> also, usb-c to usb-c does not work for me, usb-a to usb-c does.

usbfs hasn't been working for me either, never would've thought to check this, but as soon as I used a usb-a to usb-c rather than c to c, usbfs showed up... very weird

**Comment by ch40s-1** [comment]
Any news on this? I have the same problem, the workaround worked twice, but isn't very practical. Any update would be appreciated, thanks

**Comment by scorpionz89** [comment]
> Any news on this? I have the same problem, the workaround worked twice, but isn't very practical. Any update would be appreciated, thanks

Hey honestly no update, I updated to 13.2.0 and atmosphere to new 1.2.5, fresh install and same issue. Its an issue with Tintoil, I tested an older tinfoil 12 and usbfs kept working. But not practical to use older tinfoil worried it might cause issues. Only thing is to wait and maybe message tinfoil support if they have a contact email?

**Comment by ch40s-1** [comment]
Yea, same for me. Tried for hours but was pointed to a way easier method: https://switchway.xyz/tinfoil-features-tools

**Comment by scorpionz89** [comment]
> Yea, same for me. Tried for hours but was pointed to a way easier method: https://switchway.xyz/tinfoil-features-tools
> 
> Installing via USB 

Thanks, yeah that does seem like a good workaround as well. I'll give it a try.

**Comment by throwawayay** [comment]
yes, that's MTP

**Comment by hazro63** [comment]
I am getting to the step of disabling the drivers. but windows does not show me the tinfoil drivers to update them in the file manager... any fix for it?

**Comment by throwawayay** [comment]
try https://www.nirsoft.net/utils/usb_devices_view.html
