### ISSUE TITLE
[Bug] New Bug

### ISSUE THREAD

**Issue by roadhazard** [blawar/nut#366]
**Describe the bug**
I was using an older version of nut with no issues. Upgraded to Debian 11 and it no longer would launch. Got tons of errors so I thought, OK... time to upgrade to the latest version. I closed the git and got (I think) everything installed but when I run the nut_gui.py file, I get an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the steps to install nut under Linux

**Actual behaviour**
`python3 nut_gui.py 
Traceback (most recent call last):
  File "/home/roadhazard/Downloads/nut/nut_gui.py", line 8, in <module>
    from PyQt5.QtGui import (QIcon)
RuntimeError: the sip module implements API v12.0 to v12.8 but the PyQt5.QtGui module requires API v12.9
`

**Expected behaviour**
For nut to launch with no errors.

**Screenshots**

**NUT version (or git hash):**
 - Nut: 3.3
 - Git hash 7f3a0a3

**Additional context**

**Comment by droM4X** [comment]
I have a same problem on macOS Monterey.
This solved my problem: 
`pip3 install PyQt5-sip --upgrade`

Maybe it helps to you too

**Comment by introkun** [comment]
@roadhazard please try this on https://github.com/blawar/nut/issues/366#issuecomment-996676275
