### ISSUE TITLE
[Bug] it's blank while in "Nut" protocol mode

### ISSUE THREAD

**Issue by bao3** [blawar/nut#373]
**Describe the bug**
I built a Nut server, and then , open `Lithium `，Add it as "nut" protocol . But when tried open the new added source , it's blank .

The same Nut server , I added it as "nutfs" protocol , after that I tried to open the new added source , it show all the game directories .

So , how could I make the "nut" protocol to work ?

**NUT version (or git hash):**
 - Lithium: [v13.0]
 - Nut Server:[v3.3]

**Comment by crstestacc** [comment]
Did you find answer on this, nutfs if I understand not work if you have subfolders with games, games must be in root ? On old version of nut server "nut" protocol work fine.

**Comment by introkun** [comment]
@bao3 https://github.com/blawar/nut/issues/373#issuecomment-980051291 is this something that is helpful to you?
