### ISSUE TITLE
[Bug] New Bug (but in Tinfoil)

### ISSUE THREAD

**Issue by vrtice** [blawar/nut#386]
If MTP is enabled sometimes the "Installed" Folder has errors (most of the Time in the First Folder there are a lot of Subfolders that should be in the root folder).

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable MTP
2. Connect to PC
3. Check the Directory List

**Actual behaviour**
First folder (or any other) contains a lot of folders that should be in root.

**Expected behaviour**
A list of all Direcorys in the root dir.

 - Tinfoil: [13.0]

Also if you install something the Directory list ("Installed") doesn't get refreshed, makes it impossible to check if the installation worked (trying to detect NCA Errors). It would be very helpfull to be able to request a directory refresh or just update the list automatically after an installation.

**Comment by throwawayay** [comment]
MTP has no connection to nut here, that's all controlled by Tinfoil
