### ISSUE TITLE
[Bug] Fails to install dependencies on Apple ARM M1 CPU

### ISSUE THREAD

**Issue by fedorinoGore** [blawar/nut#393]
**Describe the bug**
Cannot install on Apple M1 macbook. The command  `pip3 install -r requirements.txt ` fails with error:
```
ERROR: Could not find a version that satisfies the requirement pyqt5~=5.15.1 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6)
ERROR: No matching distribution found for pyqt5~=5.15.1
```
 During the installation there is one error that logged repeatedly:
 ```
hook = backend.prepare_metadata_for_build_wheel
  AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
```
Not sure but it may happen because Qt can't compile binaries. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the instructions from README.md, section 'Installation guide (macOS)'
2. Complete all of the instruction until line `* Install all other dependencies (`pip install -r requirements.txt`)` 
3. Suffer

**Actual behaviour**
The installation fails
**Expected behaviour**
The installation should complete without errors

**Screenshots**

**NUT version (or git hash):**
 - Nut: 3.3

**Additional context**
I have a Apple M1 Pro CPU with OS X Monterey 12.0.1

**Comment by throwawayay** [comment]
You should have pyqt coming from homebrew - the section titled "Load the system python's site-packages via pyenv's python. This is required to use PyQT5 from Homebrew."

**Comment by introkun** [comment]
I have Apple M1 CPU running on OS X Monterey 12.0.1. I cannot reproduce the issue on the latest nut version from master.

**Comment by Zadowcloud** [comment]
This happened to me
