### ISSUE TITLE
[Bug] NUT GUI not loading on MacOS

### ISSUE THREAD

**Issue by zeesus** [blawar/nut#395]
I've followed the install instructions to the best of my ability and experiencing this issue. If someone could reply with step-by-step instructions it would be greatly appreciated.

could not load keys.txt, all crypto operations will fail
loaded user guest
						,;:;;,
					   ;;;;;
			   .=',	;:;;:,
			  /_', "=. ';:;:;
			  @=:__,  \,;:;:\'
				_(\.=  ;:;;\'
			   `"_(  _/="`
				`"'
loaded titledb/titles.json in 0.8079515320000001 seconds
loaded file list in 0.0007603229999999517 seconds
scanning .
organizing                                                                                                                                                
could not get new name for hbl [0000000000000000].nsp
removing empty directories
Downloading All
27444 titles scanned, downloading 0
Downloads finished
DownloadAll finished
fin
Users-MacBook-Pro:~ username$ python3 /Users/username/Downloads/nut-3.1/nut_gui.py
could not load keys.txt, all crypto operations will fail
Traceback (most recent call last):
  File "/Users/username/Downloads/nut-3.1/nut_gui.py", line 13, in <module>
    from gui.app import App
  File "/Users/usernames/Downloads/nut-3.1/gui/app.py", line 19, in <module>
    import Fs.driver.init
  File "/Users/username/Downloads/nut-3.1/Fs/driver/init.py", line 2, in <module>
    import Fs.driver.curl
  File "/Users/username/Downloads/nut-3.1/Fs/driver/curl.py", line 1, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)

**Comment by throwawayay** [comment]
ah this is a pycurl issue - Install curl with the openssl backend (brew uninstall --ignore-dependencies curl && brew install curl)

**Comment by introkun** [comment]
@zeesus please let us know if you still have the issue
