### ISSUE TITLE
Requirements issue

### ISSUE THREAD

**Issue by tasht** [blawar/nut#407]
When running pip3 install - r requirements.txt

I get ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

That was solved adding :

pbr==5.8.0
testresources==2.0.1 

to requirements.txt

**NUT version (or git hash):**
 - Nut: [3.3]

**Comment by introkun** [comment]
@tasht what is your operating system and python version? I don't see the issue in the latest Linux/Macos builds.

**Comment by tasht** [comment]
> @tasht what is your operating system and python version? I don't see the issue in the latest Linux/Macos builds.

python3 --version
Python 3.8.10

System:    Kernel: 5.4.0-99-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 

Machine:   Type: Laptop System: Apple product: MacBookPro8,1 v: 1.0 serial: <filter> Chassis: 
           type: 10 v: Mac-94245B3640C91C81 serial: <filter> 
           Mobo: Apple model: Mac-94245B3640C91C81 v: MacBookPro8,1 serial: <filter> UEFI: Apple 
           v: MBP81.88Z.0050.B00.1804101331 date: 04/10/18

**Comment by introkun** [comment]
@tasht could you please try python 3.9, 3.10 ?

**Comment by introkun** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/61635/154864402-e48a1942-5807-45d7-bd27-81b7a191dc16.png">

**Comment by tasht** [comment]
Well OK ... my OS is not up to date, and I don't have so much time to mess with an Mint update neither adding PPA's or whatever it would take to get Python3.10 on my machine.

But what I can say is that everything works fine for me now, I just had to install these two packages manually (or adding the lines in the requirements.txt file) to get the installation work fine under python3.8 .

Thank you very much for your answer byu th way.

**Comment by throwawayay** [comment]
It should work, realistically, in anything 3.7+. Glad you got it working
