### ISSUE TITLE
Run nut.exe as a service in windows

### ISSUE THREAD

**Issue by Guling85** [blawar/nut#430]
Hi,
Is it possible to run nut.exe as a windows service? i have tried but failed. 
If no can you please add this feature. It would be nice thanks in advance

**Comment by throwawayay** [comment]
try http://nssm.cc/download
run with --server flag

**Comment by Guling85** [comment]
Hi again. It is working now thanks.
My problem was that i need to start the service as "Administrator" then it worked. Thanks
