### ISSUE TITLE
[Bug] SSL certificate problem while adding remote paths

### ISSUE THREAD

**Issue by eroldru** [blawar/nut#463]
**Describe the bug**
Cannot add remote full path from my PC. I tried it several times and get the following error:

pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'Remote Full Paths'
2. Click on 'Add'
3. Fill the data for the server

**Actual behaviour**
see attached screenshot

**Expected behaviour**
Listing the dumped games.

**Screenshots**
![WN0sPXPBxc](https://user-images.githubusercontent.com/16373057/230714867-f2510d50-12b7-44de-ad59-ada85fdc6734.png)

**NUT version (or git hash):**
 - Nut: 3.3
 - Git hash: 7f3a0a3

**Additional context**
I tried troubleshooting python. Installed the latest version and over pip also installed certifi. Still the same issue.

**Comment by felipecrs** [comment]
I'm experiencing the same issue. Have you found any solution?

**Comment by eroldru** [comment]
> I'm experiencing the same issue. Have you found any solution?

I gave up and installed Tinfoil on the Switch. It was way easier and more comfortable that way anyway.

**Comment by james3126** [comment]
Unfortuantely this bug is still present. Exactly the same error when attempting to add a HTTPS location.

**Comment by zenaro147** [comment]
this error still persist, but I'm receiving different line erros 
![Captura de tela 2024-10-19 124451](https://github.com/user-attachments/assets/2d8cc8c0-e914-4d7f-acfa-d366218a8f17)

**Comment by jgsaez9** [comment]
I'm having the same issue...

**Comment by eroldru** [comment]
Closing this as it seems to have been abandoned.

**Comment by eroldru** [comment]
Marked closed correctly
