### ISSUE TITLE
[Bug] titledb.json generation fails

### ISSUE THREAD

**Issue by izenn** [blawar/nut#483]
**Describe the bug**
titledb.json generation fails

**To Reproduce**
Steps to reproduce the behaviour:
1. git clone https://github.com/blawar/nut.git nut
2. cd nut
3. python3 nut.py --import-region US --language en

**Actual behaviour**
all json files fail to download and instead create files with the content "404: Not Found"

**Expected behaviour**
titledb.json should be generated

**NUT version (or git hash):**
 - Git hash f0ef3efe1f92b221fb6ced1b9fc04d1ee6efa7b0

**Additional context**
the workaround i found was to replace
`url = 'https://raw.githubusercontent.com/blawar/nut/master/titledb/%s.%s.json' % (region, language)`
in nut/Titles.py with
`url = 'https://raw.githubusercontent.com/blawar/titledb/master/%s.%s.json' % (region, language)`

**Comment by blawar** [comment]
can you submit a PR

**Comment by izenn** [comment]
submitted.
https://github.com/blawar/nut/pull/484
