### ISSUE TITLE
[Bug] DLC Updates are moved out as "duplicate"

### ISSUE THREAD

**Issue by RyuuSlayer** [blawar/nut#488]
**To Reproduce**
Get a DLC which has a update, in this case MK8, do a scan/organize, one of the files will be moved into duplicate folder.

**Expected behaviour**
Don't do that, duh.

**Screenshots**
<img width="230" alt="image" src="https://github.com/blawar/nut/assets/33106127/6a638b65-2b31-418c-bebb-706590777224">

**Comment by throwawayay** [comment]
This is correct behavior, you only need the latest version of the dlc update
