### ISSUE TITLE
usb exception: [Errno None] b'libusb0-dll:err

### ISSUE THREAD

**Issue by cleggorz** [blawar/nut#59]
Getting this error part way through USB install With lithium

usb exception: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, win error: Cannot create a file when that file already exists.\r\n'

**Comment by neFAST** [comment]
Same error here. OS is Win10 using pyusb v1.0.2

**Comment by ronaldmickey** [comment]
except the dev fails to respond or even fix these reports
