### ISSUE TITLE
Server Authentication

### ISSUE THREAD

**Issue by Spider868** [blawar/nut#9]
Please, help me. I can't login to the server. When I start the server GUI with this command: `nut.py --server` and open `localhost:9000` in the web browser, it wants Username and Password from me. Where I can get these information? 

Thanks for your help...

**Comment by blawar** [comment]
Edit conf/users.conf.  Not that any line that starts with a # is a comment and ignored.

**Comment by Spider868** [comment]
Thanks, it worked...
